#!/usr/bin/env python3
"""E1 (BRIEF): counts by state x entity x threshold x margin band (+/-2/5/10pp),
passed/failed, for the CA/WI/TX causal core. Decides event study vs matched DiD.
Reads referendum_issuance_link.csv (has margin, passed, entity_type, rule_threshold,
rd_sample). Writes RESULTS + CSV. All numbers script output."""
import csv
from collections import defaultdict
EL="inputs/elections"
rows=list(csv.DictReader(open(f"{EL}/analysis/referendum_issuance_link.csv")))
def f(x):
    try: return float(x)
    except: return None
CORE={"CA","WI","TX"}
# cell: (state, entity_type, threshold) -> band -> {passed,failed}
cell=defaultdict(lambda: defaultdict(lambda:[0,0]))
for r in rows:
    if r["state"] not in CORE: continue
    if str(r["rd_sample"])!="1": continue
    m=f(r["threshold_centered_margin"]); p=r["passed"]
    if m is None or p not in ("0","1"): continue
    key=(r["state"],r["entity_type"],r.get("rule_threshold") or "?")
    for band in (2,5,10):
        if -band<=m<=band:
            cell[key][band][0 if p=="1" else 1]+=1

out=[["state","entity_type","threshold","band_pp","passed_n","failed_n","total"]]
L=["# E1 — margin-band counts, CA/WI/TX causal core (rd_sample=1)\n",
   "Generated by `e1_margin_bands.py`. Bands are |pct_yes − threshold| ≤ b.",
   "Cell = state × entity × threshold; decides event study (dense cutoff) vs matched DiD.\n",
   "| state | entity | thr | ±2 P/F | ±5 P/F | ±10 P/F |","|---|---|---|---|---|---|"]
for key in sorted(cell):
    st,ent,thr=key; c=cell[key]
    def pf(b): return f"{c[b][0]}/{c[b][1]}"
    L.append(f"| {st} | {ent} | {thr} | {pf(2)} | {pf(5)} | {pf(10)} |")
    for b in (2,5,10):
        out.append([st,ent,thr,b,c[b][0],c[b][1],c[b][0]+c[b][1]])
# totals per state at +/-5
L.append("\n## Totals at ±5pp (passed / failed)")
for st in ("CA","WI","TX"):
    tp=sum(c[5][0] for k,c in cell.items() if k[0]==st); tf=sum(c[5][1] for k,c in cell.items() if k[0]==st)
    L.append(f"- {st}: {tp} passed / {tf} failed  (n={tp+tf})")
L.append("\n## Read")
L.append("Dense cells (both P and F in the dozens–hundreds at ±5pp) support a local RD /")
L.append("event study; thin cells fall back to matched DiD (match on entity, purpose, amount")
L.append("decile, state, year) per the brief. See per-cell table above.")
open(f"{EL}/analysis/step0/E1_RESULTS.md","w").write("\n".join(L)+"\n")
with open(f"{EL}/analysis/step0/e1_margin_bands.csv","w",newline="") as fo:
    csv.writer(fo).writerows(out)
print("\n".join(L))
