#!/usr/bin/env python3
"""Step 0 reconcile (BRIEF 'Who Must Agree', 24 Aug 2026). Emits every number and
writes RESULTS.md. Corpus = auth_os.csv.gz (meta output/auth_paper/, read-only)."""
import csv,gzip,re
from collections import Counter,defaultdict
AUTH="inputs/corpus/auth_os.csv.gz"
EL="inputs/elections"
def blank(v): return (v is None) or (str(v).strip() in ("","NA","N/A","None","nan"))

# ---- corpus pass ----
N=0; pre2005=0; ky=0; ky_det=0
cov_blank={"has_additional_bonds_test":0,"has_rate_covenant":0,"has_optional_redemption":0,"has_sinking_fund":0}
par_amt=0; par_eff=0; par_src=Counter(); passt=Counter(); yr=Counter()
with gzip.open(AUTH,"rt") as f:
    for r in csv.DictReader(f):
        N+=1
        y=r.get("year") or ""
        try:
            if int(y)<2005: pre2005+=1
        except: pass
        if r.get("state")=="KY":
            ky+=1
            if str(r.get("auth_determined2")).lower() in ("true","1"): ky_det+=1
        for c in cov_blank:
            if blank(r.get(c)): cov_blank[c]+=1
        if not blank(r.get("par_amount")): par_amt+=1
        if not blank(r.get("par_effective")): par_eff+=1
        par_src[r.get("par_source") or "(blank)"]+=1
        passt[r.get("pol_assignment_status") or "(blank)"]+=1

# ---- B1 election files ----
FILES={"CA_CDIAC":(f"{EL}/cdiac/cdiac_elections_all.csv","Election Date"),
       "WI_DPI":(f"{EL}/wi_dpi/wi_dpi_referenda_2005_present.csv","VoteDate"),
       "TX_BRB":(f"{EL}/tx_brb/tx_brb_bond_elections_all.csv","electiondate")}
b1={}
for k,(p,dc) in FILES.items():
    rows=list(csv.DictReader(open(p))); b1[k]=len(rows)
# K4 TX BRB by year, pre/post 2019
txy=Counter()
for r in csv.DictReader(open(FILES["TX_BRB"][0])):
    m=re.search(r"(19|20)\d{2}",r.get("electiondate") or "")
    if m: txy[int(m.group(0))]+=1
tx_pre=sum(v for y,v in txy.items() if y<2019); tx_post=sum(v for y,v in txy.items() if y>=2019)

# ---- B2 crosswalk match rate by entity for CA/WI/TX ----
xw=defaultdict(lambda:[0,0])  # (state,census_type)->[tot,assigned]; state-level
statetot=defaultdict(lambda:[0,0])
for r in csv.DictReader(open(f"{EL}/crosswalk/referendum_unit_crosswalk.csv")):
    if r["state"] in ("CA","WI","TX"):
        statetot[r["state"]][0]+=1
        if r["match_status"]=="ASSIGNED": statetot[r["state"]][1]+=1

def pct(a,b): return f"{100*a/b:.1f}%" if b else "n/a"
L=[]
L.append("# Step 0 — Reconcile: repo state vs the BRIEF ('Who Must Agree')\n")
L.append("Generated by `reconcile_step0.py`. Corpus = `auth_os.csv.gz` (meta branch")
L.append("`output/auth_paper/`, read-only). All numbers are script output.\n")
L.append("## Corpus frame")
L.append(f"- auth_os documents: **{N:,}**")
L.append(f"- **K5 pre-2005 share**: {pre2005:,} docs dated <2005 = **{pct(pre2005,N)}** (out of frame by Scope A)")
L.append(f"- **K3 KY determined-n**: KY docs {ky:,}; auth_determined2==True {ky_det:,} = {pct(ky_det,ky)}")
L.append("")
L.append("## K1 — covenant-field missingness (corpus-wide, share blank)")
for c,b in cov_blank.items():
    L.append(f"- `{c}`: {b:,} blank = **{pct(b,N)}**")
L.append("")
L.append("## K2 — par coverage")
L.append(f"- `par_amount` (as stated) non-blank: {par_amt:,} = **{pct(par_amt,N)}**")
L.append(f"- `par_effective` (stated else EMMA fill) non-blank: {par_eff:,} = **{pct(par_eff,N)}**")
L.append("- `par_source` breakdown: "+", ".join(f"{k}={v:,}" for k,v in par_src.most_common()))
L.append("")
L.append("## K4 — TX BRB election coverage pre/post-2019")
L.append(f"- TX BRB rows total {b1['TX_BRB']:,}; with a parseable year {sum(txy.values()):,}")
L.append(f"- pre-2019: {tx_pre:,} · 2019+: {tx_post:,}")
L.append("- by year: "+", ".join(f"{y}:{txy[y]}" for y in sorted(txy) if y>=2014))
L.append("")
L.append("## pol_assignment_status (accountability frame)")
for k,v in passt.most_common(): L.append(f"- {k}: {v:,} ({pct(v,N)})")
L.append("")
L.append("## Build status vs B1–B4")
L.append("**B1 Election data (CA/WI/TX + 6 extra states):** DONE for the three core states —")
L.append(f"CA_CDIAC {b1['CA_CDIAC']:,} · WI_DPI {b1['WI_DPI']:,} · TX_BRB {b1['TX_BRB']:,} rows. "
         "KEEP fields present (jurisdiction, entity, date, purpose text, amount, yes-share, threshold, passed). "
         "**MISSING: the derived re-submission field** (same jurisdiction+purpose ≤4y) — not yet built.")
L.append("**B2 Crosswalk (election jurisdiction → corpus issuer → county FIPS):** DONE to the")
L.append("Census unit_id (== corpus `pol_accountable_unit_id`); issuer link via the spine; county via `county_fips`.")
for st in ("CA","WI","TX"):
    t,a=statetot[st]; L.append(f"  - {st}: {a:,}/{t:,} assigned = {pct(a,t)}")
L.append("  Fuzzy tier RA-verified (95.1%); selection bounded. **MISSING: the 20-random-pairs-per-class eyeball export.**")
L.append("**B3 Functions (chargeable flag on use lines):** NOT started — `auth_projects.csv.gz` carries the 118-label")
L.append("functional classification; the chargeable/non-chargeable/ambiguous flag is not yet added.")
L.append("**B4 Referendum-rules table:** PRELIMINARY table supplied (`rules/state_debt_rules.csv`, AI-coded, ICR 78–88%,")
L.append("verified=0). **MISSING: CA/WI/TX to full precision from state sources; ACIR A-10 (1961) / SFFF Table 48 (1986) / HMS checks.**")
L.append("")
L.append("## Anomalies flagged (not fixed)")
L.append("- Covenant fields exist as `has_*` booleans (not `additional_bonds_test`/`rate_covenant` as the codebook named them).")
L.append("- Corpus `election_date` coverage is thin (~5%); the auth tier-2 pass is expected to raise it.")
L.append("- Scope change vs prior work: BRIEF fixes the causal core at **CA/WI/TX**; MA/LA/NC/IL/IN/MN are extra coverage, not required.")

open(f"analysis/step0/RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
