#!/usr/bin/env python3
"""Standard-format regression tables for the national analysis (Section 5).
Values are transcribed from the committed results files
(analysis/N_RESULTS.md, analysis/NC_COVERAGE_RESULTS.md); every cell traces
there. Layout: numbered columns, coefficient with state-clustered SE in
parentheses beneath, significance stars, then Controls / Region FE /
Observations / Clusters rows. Rule coefficients are PRELIMINARY (pass-1
coding) and read as first-stage/descriptive, as the notes state."""
import sys
sys.path.insert(0, "exhibits"); sys.path.insert(0, "analysis")
from exlib import OUT, write_csv

def stars_t(t):
    a = abs(t)
    return "\\sig{***}" if a >= 2.576 else ("\\sig{**}" if a >= 1.96 else ("\\sig{*}" if a >= 1.645 else ""))

def reg_table(name, caption, label, dep_row, cols, coef_rows, bottom, notes):
    """cols: list of column headers. coef_rows: list of (label, [(b,se) or None]).
    bottom: list of (label, [values]). One coefficient block per row label."""
    ncol = len(cols)
    L = ["% auto-generated by make exhibits -- do not edit",
         "\\begin{table}[!htbp]\\centering\\footnotesize",
         f"\\caption{{{caption}}}\\label{{{label}}}",
         "\\setlength{\\tabcolsep}{3.5pt}",
         f"\\begin{{tabular}}{{@{{}}l{'c'*ncol}@{{}}}}", "\\toprule",
         " & " + " & ".join(f"({i+1})" for i in range(ncol)) + " \\\\"]
    if dep_row:
        L.append(" & " + " & ".join(dep_row) + " \\\\")
    L += [" & " + " & ".join(cols) + " \\\\", "\\midrule"]
    for lab, cells in coef_rows:
        l1, l2 = [lab], [""]
        for c in cells:
            if c is None:
                l1.append(""); l2.append("")
            else:
                b, se, t = c
                l1.append(f"{b:+.3f}{stars_t(t)}")
                l2.append(f"({se:.3f})")
        L.append(" & ".join(l1) + " \\\\")
        L.append(" & ".join(l2) + " \\\\ \\addlinespace")
    L.append("\\midrule")
    for lab, vals in bottom:
        L.append(lab + " & " + " & ".join(vals) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}",
          "\\begin{minipage}{0.96\\linewidth}\\vspace{2pt}\\scriptsize",
          f"\\emph{{Notes:}} {notes}",
          "\\end{minipage}", "\\end{table}"]
    open(f"{OUT}/{name}.tex", "w").write("\n".join(L) + "\n")

BASE_NOTE = ("Entity panel (90,604 local governments; estimation samples below are the "
             "corpus-active units for each outcome). Weighted least squares; Census-region "
             "fixed effects; controls: ln population (ln total revenue for special districts), "
             "homeownership, share 65+, racial fractionalisation, ln median household income, "
             "county Democratic presidential share 2020. Standard errors clustered by state in "
             "parentheses. The strict-rule indicator is the PRELIMINARY pass-1 coding "
             "(verification pass in progress), so coefficients read as first-stage associations, "
             "not causal estimates. \\sig{*} $p<0.1$, \\sig{**} $p<0.05$, \\sig{***} $p<0.01$.")

# ---- R1: first stage by entity class (from N_RESULTS.md, N1) -----------------
n1 = {
    "pooled":  (0.0988, 0.1165, 0.85, "13,928", "48"),
    "school":  (0.6902, 0.1540, 4.48, "6,857", "41"),
    "muni":    (0.2040, 0.0353, 5.77, "3,176", "37"),
    "county":  (0.1078, 0.0918, 1.17, "1,456", "43"),
    "special": (0.1756, 0.0509, 3.45, "2,439", "37"),
}
order = ["pooled", "school", "muni", "county", "special"]
reg_table(
    "R1_firststage",
    "The fifty-state first stage: strict rules and the voted share of borrowing",
    "tab:r1",
    None,
    ["Pooled", "Schools", "Municipalities", "Counties", "Special districts"],
    [("Strict referendum rule", [n1[k][:3] for k in order])],
    [("Controls", ["Yes"]*5), ("Region fixed effects", ["Yes"]*5),
     ("Entity-class dummies", ["Yes", "--", "--", "--", "--"]),
     ("Observations", [n1[k][3] for k in order]),
     ("State clusters", [n1[k][4] for k in order])],
    "Dependent variable: the voted share of the government's determined new-money dollars, "
    "2005--25, measured from the official-statement corpus (package v3). Columns (2)--(5) "
    "estimate the class-specific coefficient on its own subsample. Townships are excluded "
    "(they carry a proxy municipal rule; adding them leaves the pooled coefficient at "
    "+0.090, $t$ 0.74). " + BASE_NOTE)
write_csv("R1_firststage",
          ["column", "sample", "beta_strict", "se_cluster", "t", "n", "clusters"],
          [[i+1, k] + list(map(str, n1[k])) for i, k in enumerate(order)])

# ---- R2: substitution and the extensive margin (N2, NC_COVERAGE, N3) --------
r2 = [
    ("GO", "Pooled",            (-0.1547, 0.0861, -1.80), "14,273", "48"),
    ("GO", "GP",   (-0.2767, 0.0703, -3.93), "4,766",  "46"),
    ("NC \\$", "GP",   (-0.0872, 0.0541, -1.61), "3,340",  "46"),
    ("NC lines", "GP", (-0.0470, 0.0209, -2.25), "4,600",  "46"),
    ("Any issue", "All",    (+0.0148, 0.0295,  0.50), "56,541", "48"),
    ("ln issued", "All", (-0.2321, 0.2167, -1.07), "56,541", "48"),
]
reg_table(
    "R2_substitution",
    "Substitution away from the voted instrument, and the quiet extensive margin",
    "tab:r2",
    [x[0] for x in r2],
    [x[1] for x in r2],
    [("Strict referendum rule", [x[2] for x in r2])],
    [("Controls", ["Yes"]*6), ("Region fixed effects", ["Yes"]*6),
     ("Observations", [x[3] for x in r2]),
     ("State clusters", [x[4] for x in r2])],
    "Dependent variables: (1)--(2) GO = share of new-money dollars issued as general-obligation "
    "(GO) security; (3) share of classified project dollars in non-chargeable functions "
    "(services that cannot be billed to users); (4) the same composition measured in "
    "classified use-of-proceeds line counts, the basis robust to the coverage imbalance "
    "documented in Appendix Table A-C1 and therefore the estimate the text cites; "
    "(5) Any issue = linear probability of any corpus new-money issue 2005--25; (6) ln issued = log survey "
    "long-term debt issued per capita 2005--23 (Government Finance Database). "
    "GP = general-purpose governments (municipalities and counties); schools are near-degenerate for the "
    "non-chargeable outcome and dilute the pooled composition rows. " + BASE_NOTE)
write_csv("R2_substitution",
          ["column", "outcome", "sample", "beta_strict", "se_cluster", "t", "n", "clusters"],
          [[i+1, x[0].replace("\\$", "$"), x[1], x[2][0], x[2][1], x[2][2], x[3], x[4]]
           for i, x in enumerate(r2)])

# ---- R3 (appendix): interactions on the big-city subpanel + national moderators
r3 = [
    ("Voted \\$ share",  "TEL interaction", (0.205, None, None), (-0.185, 0.338, -0.55), "396", "34"),
    ("GO share",         "TEL interaction", (-0.109, None, None), (-1.227, 0.821, -1.49), "401", "34"),
    ("NC share",         "TEL interaction", (0.005, None, None), (-0.638, 0.494, -1.29), "358", "34"),
    ("Voted \\$ share",  "$\\times$ homeownership", (0.096, None, None), (-0.047, 0.395, -0.12), "13,928", "48"),
    ("Voted \\$ share",  "$\\times$ county Dem share", (0.194, None, None), (-0.651, 0.326, -2.00), "13,928", "48"),
]
ncol = len(r3)
L = ["% auto-generated by make exhibits -- do not edit",
     "\\begin{table}[!htbp]\\centering\\footnotesize",
     "\\caption{Institutional and demographic interactions with the rule (appendix)}\\label{tab:r3}",
     "\\setlength{\\tabcolsep}{3.5pt}",
         f"\\begin{{tabular}}{{@{{}}l{'c'*ncol}@{{}}}}", "\\toprule",
     " & " + " & ".join(f"({i+1})" for i in range(ncol)) + " \\\\",
     " & " + " & ".join(x[0] for x in r3) + " \\\\",
     " & " + " & ".join(x[1] for x in r3) + " \\\\", "\\midrule",
     "Strict rule (main effect) & " + " & ".join(f"{x[2][0]:+.3f}" for x in r3) + " \\\\ \\addlinespace",
     "Interaction & " + " & ".join(f"{x[3][0]:+.3f}{stars_t(x[3][2])}" for x in r3) + " \\\\",
     " & " + " & ".join(f"({x[3][1]:.3f})" for x in r3) + " \\\\ \\addlinespace",
     "\\midrule",
     "Observations & " + " & ".join(x[4] for x in r3) + " \\\\",
     "State clusters & " + " & ".join(x[5] for x in r3) + " \\\\",
     "\\bottomrule", "\\end{tabular}",
     "\\begin{minipage}{0.96\\linewidth}\\vspace{2pt}\\scriptsize",
     "\\emph{Notes:} Columns (1)--(3): the roughly 570-city subpanel with "
     "tax-and-expenditure-limit (TEL) stringency; the interaction asks whether TELs "
     "sharpen or blunt the rule; the subpanel is the exit-rich class where weak rule "
     "effects are predicted, so power is limited by design. Columns (4)--(5): national "
     "entity panel, strict rule interacted with the centred moderator; these moderate "
     "the first-stage channel, not the RD issuance effect (the causal moderator tests "
     "are in Section 8). " + BASE_NOTE,
     "\\end{minipage}", "\\end{table}"]
open(f"{OUT}/R3_interactions.tex", "w").write("\n".join(L) + "\n")
write_csv("R3_interactions",
          ["column", "outcome", "spec", "beta_strict", "beta_interaction", "se", "t", "n", "clusters"],
          [[i+1, x[0].replace("\\$", "$"), x[1], x[2][0], x[3][0], x[3][1], x[3][2], x[4], x[5]]
           for i, x in enumerate(r3)])

print("regression tables done: R1, R2, R3")
