#!/usr/bin/env python3
"""Shared exhibit machinery: rdrobust-convention rows, tex/csv emitters,
panel loading. Stdlib only. All exhibits regenerate from the FROZEN v3 package
via `make exhibits`."""
import csv, gzip, math, os, datetime as dt
import sys; sys.path.insert(0,"analysis")
from rdlib import rd, rd_rbc

OUT="exhibits/out"
os.makedirs(OUT,exist_ok=True)

def fl(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

_panel=None
def panel():
    global _panel
    if _panel is None:
        _panel=list(csv.DictReader(open("analysis/paper_panel.csv")))
    return _panel
def rd_frame():
    return [r for r in panel() if str(r["rd_sample"])=="1" and r["purpose_class"]=="bond_go"
            and fl(r["threshold_centered_margin"]) is not None]
def go_out(r):
    if r["issued_6y"]=="": return None
    gs=fl(r["go_share_6y"]); return 1.0 if (r["issued_6y"]=="1" and gs and gs>0) else 0.0

def rdrow(pairs, h=10.0, donut=0.0):
    """rdrobust-convention row: RBC coef, robust CI, robust p, conventional,
    bandwidth, effective N (L/R). Returns dict or None."""
    b=rd_rbc(pairs,h,donut); c=rd(pairs,h,donut)
    if not b or not c: return None
    z=abs(b["z"]); p=2*(1-_ncdf(z))
    return dict(rbc=b["tau"], lo=b["tau"]-1.96*b["se"], hi=b["tau"]+1.96*b["se"],
                p=p, conv=c["tau"], h=h, nL=b["nL"], nR=b["nR"])
def _ncdf(x):
    return 0.5*(1+math.erf(x/math.sqrt(2)))
def stars(p):
    return "\\sig{***}" if p<0.01 else ("\\sig{**}" if p<0.05 else ("\\sig{*}" if p<0.1 else ""))
def f3(x): return f"{x:+.3f}" if x is not None else "--"
def fp(x): return "$<$0.001" if x<0.001 else f"{x:.3f}"
def fn(x): return f"{x:,}"

def write_csv(name, header, rows):
    with open(f"{OUT}/{name}.csv","w",newline="") as fh:
        w=csv.writer(fh); w.writerow(header); w.writerows(rows)

def tex_table(name, caption, label, colspec, header_tex, body_lines, notes, reading):
    """booktabs, footnotesize, @{} colspec; Reading paragraph marked strippable."""
    L=["% auto-generated by make exhibits -- do not edit",
       "\\begin{table}[!htbp]\\centering\\footnotesize",
       f"\\caption{{{caption}}}\\label{{{label}}}",
       f"\\begin{{tabular}}{{@{{}}{colspec}@{{}}}}","\\toprule",
       header_tex,"\\midrule"]
    L+=body_lines
    L+=["\\bottomrule","\\end{tabular}",
        "\\begin{minipage}{0.96\\linewidth}\\vspace{2pt}\\scriptsize",
        f"\\emph{{Notes:}} {notes}",
        "\\end{minipage}",
        "% BEGIN READING (strip for submission)",
        "\\begin{minipage}{0.96\\linewidth}\\vspace{4pt}\\scriptsize",
        f"\\textbf{{Reading.}} {reading}",
        "\\end{minipage}",
        "% END READING",
        "\\end{table}"]
    open(f"{OUT}/{name}.tex","w").write("\n".join(L)+"\n")

def rd_block(lab, row):
    """Two tex lines: coefficient row + CI row (JDBK style)."""
    if row is None: return [f"{lab} & -- & -- & -- & -- & -- \\\\"]
    l1=(f"{lab} & {f3(row['rbc'])}{stars(row['p'])} & {fp(row['p'])} & "
        f"{f3(row['conv'])} & $\\pm${row['h']:.0f} & {fn(row['nL'])}/{fn(row['nR'])} \\\\")
    l2=(f" & [{row['lo']:+.3f}, {row['hi']:+.3f}] & & & & \\\\ \\addlinespace")
    return [l1,l2]
RD_HDR=("Outcome & RBC & robust $p$ & Conv. & $h$ & Eff.\\ $N$ (L/R) \\\\")
RD_CSV_HDR=["outcome","rbc","ci_lo","ci_hi","p_robust","conventional","h","n_left","n_right"]
def rd_csv_row(lab,row):
    if row is None: return [lab]+[""]*8
    return [lab,f"{row['rbc']:.4f}",f"{row['lo']:.4f}",f"{row['hi']:.4f}",
            f"{row['p']:.4f}",f"{row['conv']:.4f}",row['h'],row['nL'],row['nR']]

def parse_md_table(path, header_key):
    """Return list of row-lists from the first pipe table whose header contains header_key."""
    lines=open(path).read().splitlines()
    out=[]; inside=False
    for i,ln in enumerate(lines):
        if ln.strip().startswith("|"):
            cells=[c.strip() for c in ln.strip().strip("|").split("|")]
            if not inside:
                if header_key in ln:
                    inside=True; out.append(cells)
            else:
                if set("".join(cells))<=set("-: "): continue
                out.append(cells)
        elif inside:
            break
    return out

PANEL_NOTE=("Frame: rd\\_sample $\\cap$ GO measures, corpus package v3 (frozen). "
            "RBC = robust bias-corrected local-quadratic estimate at $h$ with robust CI "
            "(Calonico--Cattaneo--Titiunik, $\\rho=1$); conventional = local-linear, "
            "triangular kernel. Bandwidth fixed at $\\pm$10pp per the reconciliation in "
            "Appendix Table A1 (MSE-optimal row and bandwidth-sensitivity curve there). "
            "\\sig{*} $p<0.1$, \\sig{**} $p<0.05$, \\sig{***} $p<0.01$ (robust).")
