#!/usr/bin/env python3
"""Agenda-margin suite (map rows 5-7): E4, E2-by-regime, E3, TX-2019.

E4  Proposal behavior by regime (school GO measures, the comparable object):
    proposals per 100 districts per year (denominator: distinct GFD school
    GOVSids in-state, 2015), median amount, on-cycle share. H1a: stricter rules
    -> fewer, larger, better-timed proposals.
E2  Bunching by regime: [0,1) vs [-1,0) counts around each regime's own cutoff.
E3  Passage rates by threshold regime. H1a corollary: if proposals are
    engineered to win, pass rates are roughly invariant to the height of the bar.
TX-2019  In-panel rule change (separate-proposition requirement, 87th Lege
    HB experience: effective 2019): propositions per district-election and
    amount structure, TX BRB, 2014-2025. CAVEAT: the 2019 BRB reporting mandate
    also expanded coverage (K4) -- the within-election proposition count is the
    cleaner object than raw volumes.
Writes analysis/AGENDA_RESULTS.md."""
import csv, gzip, math, datetime as dt
from collections import defaultdict, Counter

def f(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
BG=[r for r in rows if r["purpose_class"]=="bond_go"]

# districts per state (GFD schools, 2015)
nd=Counter()
with gzip.open("inputs/gfd/gfd_school_compact.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        if r["Year4"]=="2015" and r["GOVSid"].strip(): nd[r["GOVSid"][:2]]+=1
GID={"CA":"05","TX":"44","WI":"50","MN":"24"}
import re
def amt_of(r): return None
# amounts from raw (reuse: CA/TX/WI)
def money(s):
    if not s: return None
    m=re.search(r"\$?\s*([0-9][0-9,]*(?:\.\d+)?)",str(s))
    if not m: return None
    try: v=float(m.group(1).replace(",",""))
    except: return None
    return v if 1e4<v<1e12 else None
amt={}
for i,r in enumerate(csv.DictReader(open("inputs/elections/cdiac/cdiac_elections_all.csv"))): amt[f"CA:{i}"]=money(r["Amount of Bond/Tax"])
for i,r in enumerate(csv.DictReader(open("inputs/elections/tx_brb/tx_brb_bond_elections_all.csv"))): amt[f"TX:{i}"]=money(r["amount"])
for i,r in enumerate(csv.DictReader(open("inputs/elections/wi_dpi/wi_dpi_referenda_2005_present.csv"))): amt[f"WI:{i}"]=money(r["Amount"])

L=["# Agenda-margin suite — E4, E2-by-regime, E3, TX-2019 (rows 5–7)\n",
   "Generated by `agenda_suite.py`.\n",
   "## E4 · School GO proposal behavior by regime (2005–2025 where covered)",
   "| state (thr) | #districts | proposals/yr | per 100 districts/yr | median amount | on-cycle share |",
   "|---|--:|--:|--:|--:|--:|"]
for st,thr,yrs in [("CA","55",21),("TX","50",21),("WI","50",21),("MN","50",6)]:
    G=[r for r in BG if r["state"]==st and r["census_type"]=="school_district" and pdate(r["election_date"])]
    n=len(G); d=nd.get(GID[st],0)
    if n==0 or d==0:
        L.append(f"| {st} ({thr}) | {d} | 0 | – | – | – |"); continue
    am=sorted(a for a in (amt.get(r["referendum_row_id"]) for r in G) if a)
    med=am[len(am)//2] if am else None
    onc=[1 for r in G if (lambda dd: dd.month==11 and dd.year%2==0)(pdate(r["election_date"]))]
    L.append(f"| {st} ({thr}) | {d} | {n/yrs:.1f} | {100*n/yrs/d:.2f} | "
             f"{'$'+format(med,',.0f') if med else '–'} | {len(onc)/n:.1%} |")
L.append("")

# E2 by regime
S=[r for r in rows if str(r["rd_sample"])=="1" and r["purpose_class"]=="bond_go" and f(r["threshold_centered_margin"]) is not None]
L+=["## E2 · Bunching at the cutoff, by regime ( [0,1) vs [−1,0) )",
    "| regime | just-above | just-below | ratio | binomial z |","|---|--:|--:|--:|--:|"]
REG=[("CA schools (55)",lambda r:r["state"]=="CA" and r["census_type"]=="school_district"),
     ("CA non-school (66.7)",lambda r:r["state"]=="CA" and r["census_type"]!="school_district"),
     ("TX (50)",lambda r:r["state"]=="TX"),("WI (50)",lambda r:r["state"]=="WI"),
     ("LA/NC/MN (50)",lambda r:r["state"] in ("LA","NC","MN"))]
for lab,sel in REG:
    G=[r for r in S if sel(r)]
    a=sum(1 for r in G if 0<=f(r["threshold_centered_margin"])<1)
    b=sum(1 for r in G if -1<=f(r["threshold_centered_margin"])<0)
    n=a+b
    z=(a-n/2)/math.sqrt(n/4) if n else 0
    L.append(f"| {lab} | {a} | {b} | {a/b if b else float('inf'):.2f} | {z:.2f} |")
L.append("")

# E3 passage rates by regime
L+=["## E3 · Passage rates by threshold regime (bond_go, margin present)",
    "| regime | n | pass rate |","|---|--:|--:|"]
for lab,sel in REG:
    G=[r for r in S if sel(r) and r["passed"] in ("0","1")]
    if G: L.append(f"| {lab} | {len(G)} | {sum(1 for r in G if r['passed']=='1')/len(G):.1%} |")
L.append("\nH1a corollary: if proposals are engineered to win, pass rates barely move with the bar's height.\n")

# TX 2019
elec=defaultdict(lambda: defaultdict(list))   # year -> (gov, date) -> [amounts]
for i,r in enumerate(csv.DictReader(open("inputs/elections/tx_brb/tx_brb_bond_elections_all.csv"))):
    m=re.search(r"(19|20)\d{2}",r.get("electiondate") or "")
    if not m: continue
    y=int(m.group(0))
    if 2014<=y<=2025:
        elec[y][(r["governmentname"],r["electiondate"])].append(money(r["amount"]))
L+=["## TX-2019 · Separate-proposition rule (in-panel rule change)",
    "Per (district × election): proposition count and amount structure. CAVEAT: the",
    "2019 BRB reporting mandate also expanded coverage (K4) — the within-election",
    "count is the cleaner object than raw volumes.",
    "| year | elections | props/election | share multi-prop | median $ per prop |","|---|--:|--:|--:|--:|"]
for y in sorted(elec):
    es=elec[y]; n=len(es)
    props=[len(v) for v in es.values()]
    allamt=sorted(a for v in es.values() for a in v if a)
    med=allamt[len(allamt)//2] if allamt else None
    L.append(f"| {y} | {n} | {sum(props)/n:.2f} | {sum(1 for p in props if p>1)/n:.1%} | "
             f"{'$'+format(med,',.0f') if med else '–'} |")
open("analysis/AGENDA_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
