#!/usr/bin/env python3
"""Attach DISTRICT-GRAIN SAIPE child-poverty to school rows in the paper panel.

Source: inputs/saipe_sd/ussd{yy}.txt (2005-2023, keyless Census downloads):
state FIPS, 5-digit SD code, name, total pop, pop 5-17, related children 5-17 in
poverty. NOTE: SAIPE school-district files carry NO income -- the district-grain
moderator gained is the CHILD POVERTY RATE (pov 5-17 / pop 5-17), an income
proxy, labeled as such. Bridge: within-state canonicalized NAME match
(census_name <-> SAIPE name); ambiguous canon collisions dropped on both sides;
match rate reported by state. Vintage: latest strictly before the vote year
(>=2005; votes before 2006 get no value). Adds columns:
  sd_childpov_rate, sd_pop517, sd_saipe_year, sd_saipe_code
Then re-runs the D5-style split: GO-issuance RD (bw ±10) by above/below-median
district child poverty (schools in rd_sample ∩ bond_go).
Writes panel in place + analysis/SAIPE_SD_RESULTS.md."""
import csv, glob, re, datetime as dt
from collections import defaultdict
import sys; sys.path.insert(0,"analysis")
from rdlib import rd

FIPS={"CA":"06","TX":"48","WI":"55","LA":"22","NC":"37","MN":"27","MA":"25","IL":"17","IN":"18"}
DROP={"SCHOOL","SCHOOLS","SCH","DISTRICT","DIST","DT","SD","AREA","PUBLIC","OF","THE",
      "INDEPENDENT","IND","ISD","CISD","CONSOLIDATED","CONS","CSD","COMM","COMMUNITY",
      "CORPORATION","CORP","METROPOLITAN","MSD","PARISH","COUNTY","BOARD","JT","JOINT",
      "NO","NUMBER"}
EXPAND={"UNIF":"UNIFIED","ELEM":"ELEMENTARY","EL":"ELEMENTARY","JR":"JUNIOR","SR":"SENIOR",
        "HTS":"HEIGHTS","SPGS":"SPRINGS","MT":"MOUNT","ST":"SAINT","CTR":"CENTER","UN":"UNION",
        "TWP":"TOWNSHIP","VLY":"VALLEY"}
def canon(s):
    s=(s or "").upper()
    s=re.sub(r"[^A-Z0-9 ]"," ",s)
    toks=[EXPAND.get(t,t) for t in s.split() if t not in DROP]
    return " ".join(toks)

# ---- parse SAIPE vintages: year -> state_fips -> canon -> (code, povrate, pop517) ----
S=defaultdict(lambda: defaultdict(dict)); AMB=defaultdict(lambda: defaultdict(set))
for path in sorted(glob.glob("inputs/saipe_sd/ussd*.txt")):
    yy=int(re.search(r"ussd(\d\d)",path).group(1)); year=2000+yy
    for line in open(path,encoding="latin-1"):
        st=line[0:2]; code=line[3:8]; name=line[9:82].strip()
        nums=line[82:].split()
        if len(nums)<3 or not st.strip().isdigit(): continue
        try: pop=float(nums[0].replace(",","")); p517=float(nums[1].replace(",","")); pov=float(nums[2].replace(",",""))
        except: continue
        c=canon(name)
        if not c: continue
        if c in S[year][st]: AMB[year][st].add(c)
        S[year][st][c]=(code,(pov/p517 if p517>0 else None),p517)
for year in S:
    for st in S[year]:
        for c in AMB[year][st]: S[year][st].pop(c,None)

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
def f(x):
    try: return float(x)
    except: return None
NEW=["sd_childpov_rate","sd_pop517","sd_saipe_year","sd_saipe_code"]
stat=defaultdict(lambda:[0,0])
for r in rows:
    for c in NEW: r[c]=""
    if r["census_type"]!="school_district" or r["state"] not in FIPS: continue
    d=(r["election_date"] or "")[:4]
    if not d.isdigit(): continue
    vy=int(d); fips=FIPS[r["state"]]; c=canon(r["census_name"])
    stat[r["state"]][0]+=1
    c_nonum=re.sub(r"\s+\d+$","",c)
    for year in range(min(vy-1,2023),2004,-1):
        d_=S.get(year,{}).get(fips,{})
        hit=d_.get(c)
        if not hit and c_nonum and c_nonum!=c:
            # TX-style trailing CoG unit number absent in SAIPE: use only if unique
            hit=d_.get(c_nonum)
        if hit:
            code,pr,p5=hit
            if pr is not None:
                r["sd_childpov_rate"]=f"{pr:.4f}"; r["sd_pop517"]=f"{p5:.0f}"
                r["sd_saipe_year"]=year; r["sd_saipe_code"]=code
                stat[r["state"]][1]+=1
            break
with open("analysis/paper_panel.csv","w",newline="") as fo:
    w=csv.DictWriter(fo,fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)

L=["# SAIPE school-district attach — district-grain child poverty (income proxy)\n",
   "Generated by `attach_saipe_sd.py`. Vintage = latest strictly pre-vote (2005+).",
   "Bridge = within-state canonicalized name; ambiguous collisions dropped.\n",
   "| state | school rows (dated) | matched | rate |","|---|--:|--:|--:|"]
for st in sorted(stat):
    n,m=stat[st]; L.append(f"| {st} | {n} | {m} | {m/n:.1%} |")
tn=sum(v[0] for v in stat.values()); tm=sum(v[1] for v in stat.values())
L.append(f"| **total** | {tn} | {tm} | {tm/tn:.1%} |")

# D5 split at district grain (schools, rd_sample, bond_go)
SS=[r for r in rows if str(r["rd_sample"])=="1" and r["purpose_class"]=="bond_go"
    and r["census_type"]=="school_district" and f(r["threshold_centered_margin"]) is not None
    and f(r["sd_childpov_rate"]) is not None]
for r in SS: r["_m"]=f(r["threshold_centered_margin"])
def go(r):
    if r["issued_6y"]=="": return None
    gs=f(r["go_share_6y"]); return 1.0 if (r["issued_6y"]=="1" and gs and gs>0) else 0.0
vals=sorted(f(r["sd_childpov_rate"]) for r in SS)
if vals:
    med=vals[len(vals)//2]
    lo=[r for r in SS if f(r["sd_childpov_rate"])<med]; hi=[r for r in SS if f(r["sd_childpov_rate"])>=med]
    L+=["\n## D5 at district grain: GO-issuance RD (bw ±10) by DISTRICT child poverty",
        f"(schools in frame with SAIPE value: n={len(SS)}; median rate {med:.3f})",
        "| subgroup | n | τ | SE | z | n L/R |","|---|--:|--:|--:|--:|---|"]
    for lab,G in [("child poverty < median",lo),("child poverty ≥ median",hi)]:
        res=rd([(r["_m"],go(r)) for r in G],10)
        if res: L.append(f"| {lab} | {len(G)} | {res['tau']:+.3f} | {res['se']:.3f} | {res['z']:.2f} | {res['nL']}/{res['nR']} |")
open("analysis/SAIPE_SD_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
