#!/usr/bin/env python3
"""Attach ACS covariates at the correct grain (map gap #1 closed with the key).

Grain ladder per unit type:
  municipal/township  -> PLACE geography via GFD FIPS_Place (deterministic)
  school_district     -> SD geography via sd_saipe_code (== ACS SD code; the
                         SAIPE name-bridge doubles as the ACS-SD key)
  county / specials   -> COUNTY geography (specials stay proxy by design)
Vintage: 2010 ACS5 for votes <=2015, 2019 ACS5 after (votes 2016-2019 overlap
the 2015-19 window -- fine for moderators, flagged for balance use).
Adds: acs_grain, acs_vintage, acs_homeown, acs_share65, acs_frac, acs_medinc.
Then the FREEHOLDER TEST: GO-issuance RD (bw ±10) split at median homeownership,
plus 65+/frac/medinc splits at proper grain. Writes analysis/ACS_RESULTS.md."""
import csv, gzip
from collections import defaultdict
import sys; sys.path.insert(0,"analysis")
from rdlib import rd

def f(x):
    try: return float(x)
    except: return None

# ACS lookup: (vintage,state_fips,geo_class,geo_id) -> derived vars
ACS={}
for r in csv.DictReader(open("analysis/cache/acs_covariates.csv")):
    gt=r["geo_type"]; gc="sd" if gt.startswith("school district") else gt
    tt,to=f(r["tenure_tot"]),f(r["tenure_own"]); pop=f(r["pop"]); p65=f(r["pop65"])
    w,b,a,h=f(r["nhwhite"]),f(r["nhblack"]),f(r["nhasian"]),f(r["hisp"])
    d=dict(homeown=(to/tt if tt else None), share65=(p65/pop if pop else None),
           medinc=f(r["medinc"]))
    if pop and pop>0 and None not in (w,b,a,h):
        oth=max(0.0,pop-w-b-a-h); sh=[w/pop,b/pop,a/pop,h/pop,oth/pop]
        d["frac"]=1-sum(x*x for x in sh)
    else: d["frac"]=None
    key=(r["vintage"],r["state_fips"],gc,r["geo_id"].zfill(5))
    if key not in ACS or gc!="sd": ACS[key]=d
    else:  # SD summary levels can duplicate a code across levels; keep first
        pass

FIPS={"CA":"06","TX":"48","WI":"55","LA":"22","NC":"37","MN":"27","MA":"25","IL":"17","IN":"18"}
# unit9 -> (place_fips5, county_fips3) from GFD
u2p={}; u2c={}
with gzip.open("analysis/cache/gfd_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        u=r["GOVSid"].strip()
        p=(r["FIPS_Place"] or "").strip()
        c=(r["FIPS_County"] or "").strip()
        if p and p!="0": u2p[u]=p.zfill(5)
        if c and c not in ("","000"): u2c[u]=c.zfill(3)

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
NEW=["acs_grain","acs_vintage","acs_homeown","acs_share65","acs_frac","acs_medinc"]
cov=defaultdict(lambda: defaultdict(int))
for r in rows:
    for c in NEW: r[c]=""
    st=r["state"]
    if st not in FIPS or not r["unit_id"]: continue
    fips=FIPS[st]; u=r["unit_id"][:9]
    vy=(r["election_date"] or "")[:4]
    if not vy.isdigit(): continue
    vint="2010" if int(vy)<=2015 else "2019"
    hit=None; grain=""
    if r["census_type"] in ("municipal","township") and u in u2p:
        hit=ACS.get((vint,fips,"place",u2p[u])); grain="place"
    if hit is None and r["census_type"]=="school_district" and r.get("sd_saipe_code"):
        hit=ACS.get((vint,fips,"sd",str(r["sd_saipe_code"]).zfill(5))); grain="sd"
    if hit is None and u in u2c:
        hit=ACS.get((vint,fips,"county",u2c[u].zfill(5))); grain="county"
    if hit:
        r["acs_grain"]=grain; r["acs_vintage"]=vint
        for k,c in [("homeown","acs_homeown"),("share65","acs_share65"),("frac","acs_frac"),("medinc","acs_medinc")]:
            if hit[k] is not None: r[c]=f"{hit[k]:.4f}" if k!="medinc" else f"{hit[k]:.0f}"
        cov[r["census_type"]][grain]+=1
with open("analysis/paper_panel.csv","w",newline="") as fo:
    w=csv.DictWriter(fo,fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)

L=["# ACS covariates at grain — homeownership (freeholder), 65+, frac, income\n",
   "Generated by `attach_acs.py`; pull via `acs_pull.py` (Census API, vintages 2010/2019).\n",
   "## Grain coverage (rows attached, by census_type)","| type | place | sd | county |","|---|--:|--:|--:|"]
for t in sorted(cov):
    L.append(f"| {t} | {cov[t].get('place',0)} | {cov[t].get('sd',0)} | {cov[t].get('county',0)} |")

S=[r for r in rows if str(r["rd_sample"])=="1" and r["purpose_class"]=="bond_go"
   and f(r["threshold_centered_margin"]) is not None]
for r in S: r["_m"]=f(r["threshold_centered_margin"])
def go(r):
    if r["issued_6y"]=="": return None
    gs=f(r["go_share_6y"]); return 1.0 if (r["issued_6y"]=="1" and gs and gs>0) else 0.0
L+=["\n## D5/H3 at proper grain: GO-issuance RD (bw ±10), split at within-frame median",
    "| moderator (grain-attached) | subgroup | n | τ | SE | z |","|---|---|--:|--:|--:|--:|"]
for key,lab in [("acs_homeown","HOMEOWNERSHIP (freeholder)"),("acs_share65","65+ share"),
                ("acs_frac","fractionalization"),("acs_medinc","median HH income")]:
    have=[r for r in S if f(r[key]) is not None]
    if len(have)<200: continue
    vals=sorted(f(r[key]) for r in have); med=vals[len(vals)//2]
    for sub,G in [("< median",[r for r in have if f(r[key])<med]),
                  ("≥ median",[r for r in have if f(r[key])>=med])]:
        res=rd([(r["_m"],go(r)) for r in G],10)
        if res: L.append(f"| {lab} | {sub} | {len(G)} | {res['tau']:+.3f} | {res['se']:.3f} | {res['z']:.2f} |")
L+=["\n## Same splits, PROPER-GRAIN ONLY (place/SD rows; county-fallback excluded)",
    "| moderator | subgroup | n | τ | SE | z |","|---|---|--:|--:|--:|--:|"]
S2=[r for r in S if r["acs_grain"] in ("place","sd")]
for key,lab in [("acs_homeown","HOMEOWNERSHIP (freeholder)"),("acs_share65","65+ share"),
                ("acs_frac","fractionalization"),("acs_medinc","median HH income")]:
    have=[r for r in S2 if f(r[key]) is not None]
    if len(have)<200: continue
    vals=sorted(f(r[key]) for r in have); med=vals[len(vals)//2]
    for sub,G in [("< median",[r for r in have if f(r[key])<med]),
                  ("≥ median",[r for r in have if f(r[key])>=med])]:
        res=rd([(r["_m"],go(r)) for r in G],10)
        if res: L.append(f"| {lab} | {sub} | {len(G)} | {res['tau']:+.3f} | {res['se']:.3f} | {res['z']:.2f} |")
open("analysis/ACS_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
