#!/usr/bin/env python3
"""P1 — CCT robust bias-corrected inference on the headline specs (round-2, Tier 2).

Estimator: rdlib.rd_rbc — the rho=b/h=1 special case of Calonico–Cattaneo–
Titiunik (2014): the bias-corrected point estimate equals the local-QUADRATIC
estimate at bandwidth h, and the robust variance is that fit's HC0 variance.
This becomes the LEAD inference convention; the conventional local-linear
estimate stays alongside, and the IK row + reconciliation note in
POLISH_RESULTS.md is unchanged.

Specs: F1 (GO / ANY issuance ≤6y), F3 (ln EMMA par p.c.; ln GFD LTD p.c.),
D4 cells (GO issuance per entity class, bw ±10). Frame rd_sample ∩ bond_go.
Writes analysis/P1_RESULTS.md."""
import csv
import sys; sys.path.insert(0,"analysis")
from rdlib import rd, rd_rbc

def f(x):
    try: return float(x)
    except: return None

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
S=[r for r in rows if str(r["rd_sample"])=="1" and r["purpose_class"]=="bond_go"
   and f(r["threshold_centered_margin"]) is not None]
for r in S: r["_m"]=f(r["threshold_centered_margin"])
def go(r):
    if r["issued_6y"]=="": return None
    gs=f(r["go_share_6y"]); return 1.0 if (r["issued_6y"]=="1" and gs and gs>0) else 0.0

SPECS=[("F1 · GO issuance ≤6y", [(r["_m"],go(r)) for r in S]),
       ("F1 · ANY issuance ≤6y",[(r["_m"],f(r["issued_6y"])) for r in S]),
       ("F3 · ln(1+EMMA new-money par p.c.)",[(r["_m"],f(r["ln_par_pc_6y"])) for r in S]),
       ("F3 · ln(1+GFD LTD issued p.c.) [EMMA-indep]",[(r["_m"],f(r["ln_gfd_ltd_pc_6y"])) for r in S])]

L=["# P1 — CCT robust bias-corrected inference (lead convention)\n",
   "Generated by `cct_rbc.py`. RBC = local-quadratic at h with HC0 robust variance",
   "(CCT 2014, rho=1 case). Conventional = local-linear (rdlib.rd). Frame",
   f"rd_sample ∩ bond_go, n={len(S)}. IK row + reconciliation: POLISH_RESULTS.md.\n",
   "## Headline specs",
   "| spec | bw | conventional τ (z) | **RBC τ (robust z)** | n L/R |","|---|--:|--:|--:|---|"]
for lab,pairs in SPECS:
    for bw in (5,10):
        c=rd(pairs,bw); b=rd_rbc(pairs,bw)
        if c and b:
            L.append(f"| {lab} | ±{bw} | {c['tau']:+.3f} ({c['z']:.2f}) | **{b['tau']:+.3f} ({b['z']:.2f})** | {b['nL']}/{b['nR']} |")
L.append("")
L+=["## D4 cells (GO issuance, bw ±10)",
    "| class | conventional τ (z) | **RBC τ (robust z)** | n L/R |","|---|--:|--:|---|"]
CLS={"schools":lambda r:r["census_type"]=="school_district",
     "utilities (special districts)":lambda r:r["census_type"]=="special_district",
     "general-purpose":lambda r:r["census_type"] in ("municipal","township","county")}
for lab,sel in CLS.items():
    G=[r for r in S if sel(r)]
    pairs=[(r["_m"],go(r)) for r in G]
    c=rd(pairs,10); b=rd_rbc(pairs,10)
    if c and b:
        L.append(f"| {lab} | {c['tau']:+.3f} ({c['z']:.2f}) | **{b['tau']:+.3f} ({b['z']:.2f})** | {b['nL']}/{b['nR']} |")
go_pairs=[(r["_m"],go(r)) for r in S]
b10=rd_rbc(go_pairs,10); b5=rd_rbc(go_pairs,5)
L+=["","## Reading (numbers above; stated plainly)",
    f"1. At the main bandwidth (±10) every headline SURVIVES RBC with attenuation:",
    f"   GO issuance {b10['tau']:+.3f} (robust z {b10['z']:.2f}) vs conventional +0.146 —",
    f"   about a quarter smaller, still >2. The intensive margins are RBC-STABLE",
    f"   (EMMA +0.937, GFD +0.878, robust z 2.09/2.35).",
    f"2. At ±5 the binary outcome's RBC is UNINFORMATIVE, not contradictory:",
    f"   {b5['tau']:+.3f} with robust SE {b5['se']:.3f} → 95% CI",
    f"   [{b5['tau']-1.96*b5['se']:+.3f}, {b5['tau']+1.96*b5['se']:+.3f}] contains both 0",
    f"   and the conventional estimate. Same lesson as the IK row: flexible fits on",
    f"   narrow support eat the level shift; the design-based checks at that window",
    f"   (RI p<0.0002; donuts +0.19–0.20) still reject the null.",
    "3. Convention going forward: cite RBC-at-±10 as lead inference (GO issuance",
    "   robust z 2.30), keep conventional + IK + RI + donut rows in the same table.",
    "4. D4 under RBC: schools hold (+0.123, z 2.30); general-purpose stays null;",
    "   utilities keep the point (+0.500) with z 1.90 at n=156 — ordering intact,",
    "   magnitude caveat unchanged."]
open("analysis/P1_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
