#!/usr/bin/env python3
"""D6 — demography of blocked majorities (round-2, Tier 1). DESCRIPTIVE.

Blocked majority := 50 < yes < applicable threshold. SCOPE CONFLICT FLAG: among
the margin states only CA has supermajority thresholds, so D6 is a WITHIN-CA
analysis (55 schools / 66.7 non-schools, per-measure threshold = pct_yes − margin).
Groups: blocked (50<yes<thr) · cleared (yes≥thr) · sub-50 (yes<50), by purpose.

Covariates at the D5 grain ladder (place/SD, county fallback — same
within-matched-ACS caveat as D5): renter share (1−acs_homeown), racial
fractionalization, median HH income, 65+ share; SAIPE child poverty (schools);
Gini (B19083, cache/acs_gini_ca.csv, same bridge: place FIPS via GFD,
SD via sd_saipe_code, county fallback; vintage 2010 for votes ≤2015 else 2019).
Differences reported with SEs. NO causal language. Writes analysis/D6_RESULTS.md."""
import csv, gzip, math
from collections import defaultdict

def f(x):
    try: return float(x)
    except: return None

# Gini lookup
G={}
for r in csv.DictReader(open("analysis/cache/acs_gini_ca.csv")):
    gc="sd" if r["geo_type"].startswith("school district") else r["geo_type"]
    G[(r["vintage"],gc,r["geo_id"])]=f(r["gini"])
# unit -> place/county fips
u2p={}; u2c={}
with gzip.open("analysis/cache/gfd_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        u=r["GOVSid"].strip()
        p=(r["FIPS_Place"] or "").strip(); c=(r["FIPS_County"] or "").strip()
        if p and p!="0": u2p[u]=p.zfill(5)
        if c and c not in ("","000"): u2c[u]=c.zfill(5)

rows=[r for r in csv.DictReader(open("analysis/paper_panel.csv"))
      if r["state"]=="CA" and r["purpose_class"]=="bond_go"
      and f(r["pct_yes"]) is not None and f(r["threshold_centered_margin"]) is not None]
def gini_of(r):
    vy=(r["election_date"] or "")[:4]
    vint="2010" if vy.isdigit() and int(vy)<=2015 else "2019"
    u=(r["unit_id"] or "")[:9]
    if r["census_type"] in ("municipal","township") and u in u2p:
        v=G.get((vint,"place",u2p[u]))
        if v is not None: return v
    if r["census_type"]=="school_district" and r["sd_saipe_code"]:
        v=G.get((vint,"sd",r["sd_saipe_code"].zfill(5)))
        if v is not None: return v
    if u in u2c: return G.get((vint,"county",u2c[u]))
    return None
for r in rows:
    py=f(r["pct_yes"]); m=f(r["threshold_centered_margin"])
    thr=round(py-m,1)
    r["_grp"]="blocked" if 50<py<thr else ("cleared" if py>=thr else "sub50")
    ho=f(r["acs_homeown"])
    r["_v"]=dict(renter=(1-ho if ho is not None else None),
                 frac=f(r["acs_frac"]), medinc=f(r["acs_medinc"]),
                 share65=f(r["acs_share65"]), childpov=f(r["sd_childpov_rate"]),
                 gini=gini_of(r))

def mse(vals):
    v=[x for x in vals if x is not None]
    if len(v)<2: return None,None,len(v)
    mu=sum(v)/len(v)
    sd=math.sqrt(sum((x-mu)**2 for x in v)/(len(v)-1))
    return mu,sd/math.sqrt(len(v)),len(v)

VARS=[("renter","renter share"),("gini","Gini (B19083)"),("frac","fractionalization"),
      ("medinc","median HH income $"),("share65","65+ share"),("childpov","SAIPE child poverty (schools)")]
L=["# D6 — demography of blocked majorities (DESCRIPTIVE; within CA)\n",
   "Generated by `d6_blocked_majorities.py`. SCOPE FLAG: blocked majorities",
   "(50<yes<threshold) exist only under supermajority rules — among margin states",
   "that is CA alone; every cell below is CA. Grain/matching caveat as in D5:",
   "covariates are within-matched ACS/SAIPE at the D5 grain ladder, not",
   "representative of unmatched units. Differences are DESCRIPTIVE — blocked-majority",
   "places differ compositionally; nothing here is a discontinuity estimate.\n"]
for pur,sel in [("schools (thr 55)",lambda r:r["census_type"]=="school_district"),
                ("non-schools (thr 66.7)",lambda r:r["census_type"]!="school_district")]:
    P=[r for r in rows if sel(r)]
    ns={g:sum(1 for r in P if r["_grp"]==g) for g in ("blocked","cleared","sub50")}
    L.append(f"## {pur} — n: blocked {ns['blocked']}, cleared {ns['cleared']}, sub-50 {ns['sub50']}")
    L.append("| covariate | blocked | cleared | sub-50 | blocked−cleared (SE) | blocked−sub50 (SE) |")
    L.append("|---|--:|--:|--:|--:|--:|")
    for k,lab in VARS:
        if k=="childpov" and "non" in pur: continue
        cells={};
        for g in ("blocked","cleared","sub50"):
            cells[g]=mse([r["_v"][k] for r in P if r["_grp"]==g])
        def fmt(c):
            mu,se,n=c
            if mu is None: return "–"
            return f"{mu:,.0f} (n={n})" if k=="medinc" else f"{mu:.3f} (n={n})"
        def dfmt(a,b):
            if a[0] is None or b[0] is None: return "–"
            d=a[0]-b[0]; se=math.sqrt(a[1]**2+b[1]**2)
            star="*" if abs(d)>1.96*se else ""
            return (f"{d:+,.0f} ({se:,.0f}){star}" if k=="medinc" else f"{d:+.3f} ({se:.3f}){star}")
        L.append(f"| {lab} | {fmt(cells['blocked'])} | {fmt(cells['cleared'])} | {fmt(cells['sub50'])} "
                 f"| {dfmt(cells['blocked'],cells['cleared'])} | {dfmt(cells['blocked'],cells['sub50'])} |")
    L.append("")
L.append("`*` = |diff| > 1.96·SE. Verdict: DESCRIPTIVE.")
L.append("\nRead (compositional, not causal): on renter share, diversity and inequality,")
L.append("blocked-majority places sit BETWEEN the sub-50 places and the cleared places —")
L.append("the supermajority bar binds in mid-composition electorates, and among schools the")
L.append("blocked places are the poorer ones (−$3.8k vs cleared, SE 1.5k). The demographic")
L.append("cost of the higher bar falls on majorities in less affluent, mid-diversity places.")
open("analysis/D6_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
