#!/usr/bin/env python3
"""D2 + D3: what happens after a refusal.

D2 — failure taxonomy. Among FAILED bond_go measures with a margin:
  majority-failure  50 < pct_yes < threshold   (supermajority states: CA)
  minority-failure  pct_yes < 50
  Compare: re-submission ≤4y, pass rate of the return, issuance ≤6y, council share.
  PLUS the signal test: among CA failed school measures (threshold 55), RD at the
  50% line (margin50 = pct_yes − 50, sample pct_yes<55): both sides FAIL, so a
  jump in re-submission at 50 identifies the informational value of majority
  support, free of any institutional discontinuity.

D3 — re-submission hazard. For failed bond_go measures: discrete-time hazard of a
  same-unit, same-class return by years-since-failure 1..4 (risk set censored at
  the state's last observed election date); pass rate and amount ratio
  (return/original) where amounts exist (CA/TX/WI).
Writes analysis/FAILURE_PATHS_RESULTS.md. All numbers from this script."""
import csv, re, math, datetime as dt
from collections import defaultdict, Counter
import sys; sys.path.insert(0,"analysis")
from rdlib import rd

EL="inputs/elections"
rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
def f(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

# ---- amounts per rid (CA/TX/WI) ----
def money(s):
    if not s: return None
    m=re.search(r"\$?\s*([0-9][0-9,]*(?:\.\d+)?)",str(s))
    if not m: return None
    try: v=float(m.group(1).replace(",",""))
    except: return None
    return v if 1e4<v<1e12 else None
amt={}
for i,r in enumerate(csv.DictReader(open(f"{EL}/cdiac/cdiac_elections_all.csv"))):
    amt[f"CA:{i}"]=money(r["Amount of Bond/Tax"])
for i,r in enumerate(csv.DictReader(open(f"{EL}/tx_brb/tx_brb_bond_elections_all.csv"))):
    amt[f"TX:{i}"]=money(r["amount"])
for i,r in enumerate(csv.DictReader(open(f"{EL}/wi_dpi/wi_dpi_referenda_2005_present.csv"))):
    amt[f"WI:{i}"]=money(r["Amount"])

# ---- sequences per (unit, class) over ALL measures (any purpose_class kept separate) ----
seq=defaultdict(list)
last_by_state=defaultdict(lambda: dt.date(1900,1,1))
P={}
for r in rows:
    d=pdate(r["election_date"])
    if d and d>last_by_state[r["state"]]: last_by_state[r["state"]]=d
    if r["unit_id"] and d:
        seq[(r["unit_id"],r["purpose_class"])].append(
            (d,r["referendum_row_id"],r["passed"],f(r["pct_yes"]),amt.get(r["referendum_row_id"])))
for k in seq: seq[k].sort()

# ---- D3 hazard over failed bond_go (rd_sample not required: use all margin states) ----
FAILS=[]
for r in rows:
    if r["purpose_class"]!="bond_go" or r["passed"]!="0": continue
    d=pdate(r["election_date"])
    if not d or not r["unit_id"]: continue
    FAILS.append(r)
def next_return(r):
    d=pdate(r["election_date"])
    lst=seq[(r["unit_id"],r["purpose_class"])]
    for dj,rj,pj,py,aj in lst:
        if dj>d: return (dj-d).days/365.25, pj, aj
    return None,None,None

haz_n=[0]*4; haz_k=[0]*4          # year buckets 0-1,1-2,2-3,3-4
ret_pass=ret_tot=0; ratios=[]
t2r=[]
for r in FAILS:
    d=pdate(r["election_date"]); st=r["state"]
    obs=(last_by_state[st]-d).days/365.25
    t,pj,aj=next_return(r)
    for y in range(4):
        if obs>=y+1 and (t is None or t>y):    # at risk through year y+1
            haz_n[y]+=1
            if t is not None and y<t<=y+1: haz_k[y]+=1
    if t is not None and t<=4:
        t2r.append(t); ret_tot+=1
        if pj=="1": ret_pass+=1
        a0=amt.get(r["referendum_row_id"])
        if a0 and aj: ratios.append(aj/a0)
t2r.sort()
med=t2r[len(t2r)//2] if t2r else None
ratios.sort()

L=["# Failure paths — D2 taxonomy + D3 re-submission hazard (bond_go)\n",
   f"Failed GO-bond measures with unit+date: **{len(FAILS)}**. Generated by `failure_paths.py`.\n",
   "## D3 · Re-submission hazard (same unit, same purpose class)",
   "| years since failure | at risk | returns | hazard |","|---|--:|--:|--:|"]
for y in range(4):
    L.append(f"| {y}–{y+1} | {haz_n[y]} | {haz_k[y]} | {haz_k[y]/haz_n[y]:.1%} |" if haz_n[y] else f"| {y}–{y+1} | 0 | – | – |")
cum=1.0
for y in range(4):
    if haz_n[y]: cum*=1-haz_k[y]/haz_n[y]
L+= [f"\nKaplan–Meier share re-submitting within 4y: **{1-cum:.1%}**; median time-to-return "
     f"(among ≤4y returns): **{med:.2f} y**." if med else "",
     f"Returning measures that PASS: **{ret_pass}/{ret_tot} = {ret_pass/ret_tot:.1%}**." if ret_tot else "",
     (f"Amount ratio return/original (n={len(ratios)}): median **{ratios[len(ratios)//2]:.2f}**, "
      f"share smaller than original **{sum(1 for x in ratios if x<0.999)/len(ratios):.1%}**.") if ratios else "",""]

# ---- D2 taxonomy ----
def thr_of(r):
    t=f(r["rule_threshold"])
    if r["state"]=="CA":
        m=f(r["threshold_centered_margin"]); py=f(r["pct_yes"])
        if m is not None and py is not None: return round(py-m,2)   # per-measure CDIAC threshold
    return t if t else 50.0
maj=[]; mino=[]
for r in FAILS:
    py=f(r["pct_yes"])
    if py is None: continue
    th=thr_of(r)
    if th and th>50 and 50<py<th: maj.append(r)
    elif py<50: mino.append(r)
def rate(g,col,val="1"):
    gg=[x for x in g if x[col]!=""]
    return (sum(1 for x in gg if str(x[col])==val)/len(gg), len(gg)) if gg else (float("nan"),0)
# within-CA versions (removes the state-composition confound: maj-fails are all CA)
majCA=[r for r in maj if r["state"]=="CA"]; minoCA=[r for r in mino if r["state"]=="CA"]
L+=["## D2 · Majority-failures vs minority-failures",
    f"majority-failures (50<yes<threshold): **{len(maj)}** (CA supermajority regimes); "
    f"minority-failures (yes<50): **{len(mino)}**.",
    "**Pooled comparison is confounded** (majority-fails are all CA; minority-fails pool "
    "TX/WI/CA) — the WITHIN-CA panel below is the valid contrast.",
    "| outcome | majority-fail | minority-fail |","|---|--:|--:|"]
for col,lab in [("resubmitted_4y","re-submitted ≤4y"),("issued_6y","any issuance ≤6y")]:
    a,na=rate(maj,col); b,nb=rate(mino,col)
    L.append(f"| {lab} | {a:.1%} (n={na}) | {b:.1%} (n={nb}) |")
def meanc(g,col):
    v=[f(x[col]) for x in g if f(x[col]) is not None]
    return (sum(v)/len(v),len(v)) if v else (float("nan"),0)
a,na=meanc(maj,"council_share_6y"); b,nb=meanc(mino,"council_share_6y")
L.append(f"| council share of window docs | {a:.3f} (n={na}) | {b:.3f} (n={nb}) |")
L.append("")
L+=["### Within CA only (valid contrast)","| outcome | majority-fail | minority-fail |","|---|--:|--:|"]
for col,lab in [("resubmitted_4y","re-submitted ≤4y"),("issued_6y","any issuance ≤6y")]:
    a,na=rate(majCA,col); b,nb=rate(minoCA,col)
    L.append(f"| {lab} | {a:.1%} (n={na}) | {b:.1%} (n={nb}) |")
a,na=meanc(majCA,"council_share_6y"); b,nb=meanc(minoCA,"council_share_6y")
L.append(f"| council share of window docs | {a:.3f} (n={na}) | {b:.3f} (n={nb}) |")
L.append("")
# regime x purpose conditioning (map row 12): within CA, split by cutoff regime
L+=["### Within CA, by cutoff regime (regime × purpose held fixed)",
    "| regime | outcome | majority-fail | minority-fail |","|---|---|--:|--:|"]
for regime,sel in [("CA schools (thr 55)",lambda r:r["census_type"]=="school_district"),
                   ("CA non-school (thr 66.7)",lambda r:r["census_type"]!="school_district")]:
    mj=[r for r in majCA if sel(r)]; mn=[r for r in minoCA if sel(r)]
    for col,lab in [("resubmitted_4y","re-submitted ≤4y"),("issued_6y","any issuance ≤6y")]:
        a,na=rate(mj,col); b,nb=rate(mn,col)
        L.append(f"| {regime} | {lab} | {a:.1%} (n={na}) | {b:.1%} (n={nb}) |")
L.append("")

# ---- D2b signal RD at 50 among CA failed school measures (threshold 55) ----
CA=[r for r in rows if r["state"]=="CA" and r["purpose_class"]=="bond_go" and r["passed"]=="0"
    and r["census_type"]=="school_district" and f(r["pct_yes"]) is not None
    and abs(round((f(r["pct_yes"]) or 0)-(f(r["threshold_centered_margin"]) or 0)-55,1))<0.2]  # threshold==55 measures
pairs=[((f(r["pct_yes"])-50), 1.0 if str(r["resubmitted_4y"])=="1" else (0.0 if str(r["resubmitted_4y"])=="0" else None)) for r in CA]
L+=["## D2b · Signal test: RD at the 50% line among CA FAILED school measures (thr 55)",
    f"Sample: CA school bond failures with yes<55 (both sides of 50 FAIL): n={len(CA)}.",
    "| outcome | bw | τ | SE | z | n L/R |","|---|--:|--:|--:|--:|---|"]
for bw in (3,5):
    res=rd(pairs,bw)
    if res:
        L.append(f"| re-submitted ≤4y | ±{bw} | {res['tau']:+.3f} | {res['se']:.3f} | {res['z']:.2f} | {res['nL']}/{res['nR']} |")
L.append("\nBoth sides of 50 fail institutionally — a jump here is the informational value of"
         "\nmajority support (the board reads the signal), clean of any legal discontinuity.")

open("analysis/FAILURE_PATHS_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
