#!/usr/bin/env python3
"""Extend the survey (GFD-style) outcome to FY2024 from the Census July-2025
S&L Public Use Individual Unit Files (2022/23/24, copied from municipal-analysis).

The public-use ID is 12 chars: state(2)+type(1)+county(3)+newid(6) -- NOT the
classic CoG unit number -- so the bridge is (state,type,county)+canonicalized
name via Fin_PID_{yr}.txt, restricted to our crosswalked units.
Item-code mapping is VALIDATED, not assumed: candidate 29U (=LTD issued) and
49U (=LTD outstanding) parsed from the 2022 file are compared to GFD's 2022
Total_LTD_Issued / Total_LTD_Out for matched units; the mapping is accepted only
if the agreement is tight. Then FY2024 (and 2023 as cross-check) are emitted to
analysis/cache/iuf_extension.csv (unit9, year, ltd_iss_k) for build_outcomes to
merge. Writes analysis/IUF_RESULTS.md."""
import csv, gzip, re
from collections import defaultdict

IUF="/tmp/claude-0/-home-user-muni-universe/00365a83-f472-577e-acb7-f3d77468ac75/scratchpad/iuf"
DIRS={2022:f"{IUF}/2022_Individual_Unit_files",2023:f"{IUF}/2023_Individual_Unit_Files",2024:f"{IUF}/2024_Individual_Unit_Files"}
FIN={2022:"2022FinEstDAT_07152026modp.txt",2023:"2023FinEstDAT_07152026modp.txt",2024:"2024FinEstDAT_07152026modp.txt"}
PID={2022:"Fin_PID_2022.txt",2023:"Fin_PID_2023.txt",2024:"Fin_PID_2024.txt"}

DROP={"OF","THE","CITY","TOWN","VILLAGE","TOWNSHIP","COUNTY","PARISH","BOROUGH",
      "SCHOOL","SCHOOLS","SCH","DISTRICT","DIST","DT","INDEPENDENT","IND","ISD","CISD",
      "CONSOLIDATED","CONS","COMMUNITY","COMM","UNIT","PUBLIC","CORPORATION","CORP","NO","NUMBER"}
def canon(s):
    s=(s or "").upper(); s=re.sub(r"[^A-Z0-9 ]"," ",s)
    return " ".join(t for t in s.split() if t not in DROP)

def f(x):
    try: return float(x)
    except: return None

# our units: unit9 -> census_name (panel) + FIPS state/county (GFD)
uname={}
for r in csv.DictReader(open("analysis/paper_panel.csv")):
    if r["unit_id"]: uname[r["unit_id"][:9]]=r["census_name"]
ufips={}
with gzip.open("analysis/cache/gfd_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        st=(r["FIPS_Code_State"] or "").strip().zfill(2)
        ct=(r["FIPS_County"] or "").strip().zfill(3)
        if st!="00" and ct!="000": ufips[r["GOVSid"].strip()]=(st,ct)
# bridge: IUF id12 prefix is FIPS state(2)+type(1)+FIPS county(3); key on that + canon name
bidx={}; coll=set()
for u,nm in uname.items():
    fp=ufips.get(u)
    if not fp: continue
    k=(fp[0]+u[2]+fp[1],canon(nm))
    if k in bidx: coll.add(k)
    else: bidx[k]=u
for k in coll: bidx.pop(k,None)

def load_year(yr,items=("29U","49U")):
    # id12 -> name (PID), then id12 -> {item: amount}
    names={}
    for line in open(f"{DIRS[yr]}/{PID[yr]}",encoding="latin-1"):
        names[line[:12]]=line[12:76].strip()
    vals=defaultdict(dict)
    for line in open(f"{DIRS[yr]}/{FIN[yr]}",encoding="latin-1"):
        it=line[12:15].strip()
        if it in items:
            vals[line[:12]][it]=f(line[15:27])
    # map to unit9
    out={}
    for id12,v in vals.items():
        nm=names.get(id12)
        if not nm: continue
        u=bidx.get((id12[:6],canon(nm)))
        if u: out[u]=v
    return out,len(vals),len(out)

L=["# IUF extension — survey outcome to FY2024\n","Generated by `iuf_extension.py`.\n"]
# ---- validation on 2022 vs GFD ----
m22,nfin,nmap=load_year(2022)
gfd22={}
with gzip.open("analysis/cache/gfd_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        if r["Year4"]=="2022":
            gfd22[r["GOVSid"].strip()]=(f(r["Total_LTD_Issued"]),f(r["Total_LTD_Out"]))
pairs_iss=[]; pairs_out=[]
for u,v in m22.items():
    g=gfd22.get(u)
    if not g: continue
    if v.get("29U") is not None and g[0] is not None: pairs_iss.append((v["29U"],g[0]))
    if v.get("49U") is not None and g[1] is not None: pairs_out.append((v["49U"],g[1]))
def agree(pairs):
    n=len(pairs); ex=sum(1 for a,b in pairs if abs(a-b)<=max(1,0.005*max(abs(a),abs(b))))
    return n,ex
ni,ei=agree(pairs_iss); no,eo=agree(pairs_out)
L+=["## Item-code validation (2022 IUF vs GFD 2022, matched units)",
    f"- bridge: {nmap}/{nfin} IUF units mapped to crosswalked units (state+type+county+name)",
    f"- **29U vs Total_LTD_Issued: {ei}/{ni} within 0.5% ({ei/ni:.1%})**" if ni else "- 29U: no pairs",
    f"- **49U vs Total_LTD_Out: {eo}/{no} within 0.5% ({eo/no:.1%})**" if no else "- 49U: no pairs",""]
ok = ni>200 and ei/ni>0.9
L.append(f"Mapping {'ACCEPTED' if ok else 'REJECTED — do not use'}: 29U = Total LTD issued ($k), 49U = LTD outstanding.\n")
if ok:
    rows=[["unit9","year","ltd_iss_k","ltd_out_k"]]
    for yr in (2023,2024):
        m,_,nm_=load_year(yr)
        for u,v in m.items():
            rows.append([u,yr,f"{v.get('29U','')}",f"{v.get('49U','')}"])
        L.append(f"FY{yr}: {nm_} crosswalked units carried.")
    with open("analysis/cache/iuf_extension.csv","w",newline="") as fo:
        csv.writer(fo).writerows(rows)
    L.append("\nwrote analysis/cache/iuf_extension.csv (merged by build_outcomes for years missing in GFD).")
open("analysis/IUF_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
