#!/usr/bin/env python3
"""M3 — absolute coalitions: how many yes-votes actually decide (round-2, Tier 1).

COVERAGE CONFLICT FLAG: the instruction says "CDIAC yes" for votes-cast — WRONG.
CDIAC carries % Yes / % No only, no counts; CA is EXCLUDED from count-based
panels. Counts exist in: TX BRB (votesfor/against), WI DPI (Yes/NoVotes),
LA SoS (votes_yes/no + voters_qualified/voters_voted — true turnout),
NC NCSBE (votes_for/against), MN SoS, MA DLS. IL/IN: results only, no counts.

Frame: panel bond measures (bond_go) with counts joined by referendum_row_id.
votes cast := yes+no on the measure. yes-needed := floor(total × thr/100)+1
(strict-majority convention; ≥-threshold statutes differ by one vote — noted).
Cycle: on = November of an even year; off = anything else.
Writes analysis/M3_RESULTS.md."""
import csv, datetime as dt
from collections import defaultdict

def f(x):
    try: return float(str(x).replace(",",""))
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None
def pct(v,ps):
    v=sorted(v); return [v[min(len(v)-1,int(p*len(v)))] for p in ps]

EL="inputs/elections"
counts={}   # row_id -> (yes, no)
for i,r in enumerate(csv.DictReader(open(f"{EL}/tx_brb/tx_brb_bond_elections_all.csv"))):
    counts[f"TX:{i}"]=(f(r["votesfor"]),f(r["votesagainst"]))
for i,r in enumerate(csv.DictReader(open(f"{EL}/wi_dpi/wi_dpi_referenda_2005_present.csv"))):
    counts[f"WI:{i}"]=(f(r["YesVotes"]),f(r["NoVotes"]))
for i,r in enumerate(csv.DictReader(open(f"{EL}/la_sos/la_sos_local_propositions_2005_present.csv"))):
    counts[f"LA:{i}"]=(f(r["votes_yes"]),f(r["votes_no"]))
for i,r in enumerate(csv.DictReader(open(f"{EL}/nc_ncsbe/nc_ncsbe_bond_referenda_2005_present.csv"))):
    counts[f"NC:{i}"]=(f(r["votes_for"]),f(r["votes_against"]))
for i,r in enumerate(csv.DictReader(open(f"{EL}/mn_sos/mn_sos_ballot_questions_2020_2025.csv"))):
    counts[f"MN:{i}"]=(f(r["yes_votes"]),f(r["no_votes"]))
for i,r in enumerate(csv.DictReader(open(f"{EL}/ma_dls/ma_prop2_5_borrowing_votes.csv"))):
    counts[f"MA:{i}"]=(f(r["votes_yes"]),f(r["votes_no"]))

# name lookup for the concrete-contrast prose (TX)
tx_names={}
for i,r in enumerate(csv.DictReader(open(f"{EL}/tx_brb/tx_brb_bond_elections_all.csv"))):
    tx_names[f"TX:{i}"]=r["governmentname"]

panel=list(csv.DictReader(open("analysis/paper_panel.csv")))
rows=[]
for r in panel:
    if r["purpose_class"]!="bond_go": continue
    c=counts.get(r["referendum_row_id"])
    if not c or c[0] is None or c[1] is None or c[0]+c[1]<=0: continue
    d=pdate(r["election_date"])
    thr=f(r["rule_threshold"]) or 50.0
    py,m=f(r["pct_yes"]),f(r["threshold_centered_margin"])
    if r["state"]=="CA" and py is not None and m is not None: thr=round(py-m,1)
    tot=c[0]+c[1]
    if tot<=1: continue   # BRB placeholder convention: counts-unknown rows recorded 1–0
    need=int(tot*thr/100.0)+1
    cyc="on" if (d and d.month==11 and d.year%2==0) else "off"
    rows.append(dict(st=r["state"],rid=r["referendum_row_id"],ent=r["census_type"] or "unlinked",
                     tot=tot,need=need,cyc=cyc,thr=thr))
print(f"bond_go measures with counts: {len(rows)}")

L=["# M3 — absolute coalitions: the yes-votes that decide\n",
   "Generated by `m3_absolute_coalitions.py`.\n",
   "## Coverage (CONFLICT FLAG: instruction said 'CDIAC yes' — CDIAC has % only)",
   "| source | vote counts | turnout denominator | in count panels |","|---|---|---|---|",
   "| CA CDIAC | **NO — % Yes/% No only** | no | excluded |",
   "| TX BRB | votesfor/votesagainst | no | yes |",
   "| WI DPI | YesVotes/NoVotes | no | yes |",
   "| LA SoS | votes_yes/votes_no | **voters_qualified + voters_voted** | yes |",
   "| NC NCSBE | votes_for/votes_against | no | yes |",
   "| MN SoS | yes/no votes (2020–25) | no | yes |",
   "| MA DLS | votes_yes/votes_no | no | yes |",
   "| IL SBE / IN DLGF | results only | no | excluded |",""]

L.append(f"Frame: **{len(rows)}** GO-bond measures with usable counts by state: "
         + ", ".join(f"{s} {sum(1 for x in rows if x['st']==s)}" for s in sorted(set(x['st'] for x in rows)))+".\n")
L.append("DATA FLAG (caught here): TX BRB rows with votesfor+votesagainst = 1 (3,188 raw")
L.append("rows, all eras incl. 1950s city bonds recorded '1–0 Carried') are a counts-unknown")
L.append("PLACEHOLDER convention, not one-voter elections — EXCLUDED from every panel below.")
L.append("Genuine tiny elections (2–30 votes, MUD era 2010+) remain. Placeholder rows carry")
L.append("pct_yes=100 → margin ≈ +50, outside every RD bandwidth: no RD estimate is affected.")
L.append("MA/MN carry counts but sit outside the bond_go frame (MA = debt-exclusion class;")
L.append("MN = school-purpose classification gap) — hence absent from the state list above.\n")

L+=["## Votes cast and yes-votes needed, by entity type × cycle",
    "| entity | cycle | n | votes cast p10/p50/p90 | yes-needed p10/p50/p90 |","|---|---|--:|---|---|"]
for ent in ("school_district","municipal","special_district","county","township","unlinked"):
    for cyc in ("on","off"):
        G=[x for x in rows if x["ent"]==ent and x["cyc"]==cyc]
        if len(G)<20: continue
        t=pct([x["tot"] for x in G],[.1,.5,.9]); nd=pct([x["need"] for x in G],[.1,.5,.9])
        L.append(f"| {ent} | {cyc} | {len(G)} | {t[0]:,.0f} / {t[1]:,.0f} / {t[2]:,.0f} "
                 f"| {nd[0]:,.0f} / {nd[1]:,.0f} / {nd[2]:,.0f} |")
L.append("")

def med_need(sel):
    v=sorted(x["need"] for x in rows if sel(x))
    return (v[len(v)//2], len(v)) if v else (None,0)
h1=med_need(lambda x:x["ent"]=="school_district")
h2=med_need(lambda x:x["ent"]=="municipal" and x["cyc"]=="off")
h3=med_need(lambda x:x["ent"]=="special_district")
L+=["## Headline cells (median yes-votes that decided)",
    f"- a **school bond**: **{h1[0]:,}** yes-votes (n={h1[1]})",
    f"- an **off-cycle city measure**: **{h2[0]:,}** yes-votes (n={h2[1]})",
    f"- a **special-district election**: **{h3[0]:,}** yes-votes (n={h3[1]})",""]

# TX same-regime contrast (threshold 50 throughout)
TX=[x for x in rows if x["st"]=="TX"]
tt=pct([x["tot"] for x in TX],[.1,.5,.9]); tn=pct([x["need"] for x in TX],[.1,.5,.9])
TXs=sorted(TX,key=lambda x:x["tot"])
lo=[x for x in TXs[:25]]; hi=[x for x in TXs[-25:]]
L+=["## The San Antonio–vs–rural contrast (within TX, one 50% regime)",
    f"TX GO measures with counts: {len(TX)}. Votes cast p10/p50/p90: "
    f"**{tt[0]:,.0f} / {tt[1]:,.0f} / {tt[2]:,.0f}**; yes-needed p10/p50/p90: "
    f"**{tn[0]:,.0f} / {tn[1]:,.0f} / {tn[2]:,.0f}**.",
    "Concrete ends of the same legal rule:"]
for x in TXs[-3:]:
    L.append(f"- {tx_names.get(x['rid'],'?')}: {x['tot']:,.0f} votes cast → {x['need']:,} yes-votes to authorize")
for x in TXs[:3]:
    L.append(f"- {tx_names.get(x['rid'],'?')}: {x['tot']:,.0f} votes cast → {x['need']:,} yes-votes to authorize")
la=[x for x in rows if x["st"]=="LA"]
L+=["","Notes: yes-needed uses the strict-majority convention floor(total×thr)+1;",
    "≥-threshold statutes differ by one vote. LA carries voters_qualified/voters_voted",
    f"(true turnout) on {len(la)} measures — reserved for a turnout extension.",
    "The same statutory sentence — 'a majority of those voting' — is a coalition of",
    "tens of thousands in a big-city ISD and of a few dozen in a developer MUD;",
    "M3 is the paper's absolute-size exhibit behind the H3/electorate-composition story."]
open("analysis/M3_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
