#!/usr/bin/env python3
"""Manipulation checks for the RD (rd_sample ∩ bond_go):
 1. McCrary (2008) density test: bin the margin (width 0.5pp), local-linear fit
    of the density on each side (triangular kernel, bandwidth h), discontinuity
    θ = ln f(0+) − ln f(0−), SE by delta method from the two intercept variances.
 2. Donut-RD: re-estimate the main RD dropping |margin|<=delta (0.5, 1, 2pp) —
    if the effect survives excluding the region where manipulation could live,
    bunching cannot explain it.
Writes analysis/MCCRARY_DONUT_RESULTS.md. Pure stdlib."""
import csv, math
from collections import Counter

rows=[r for r in csv.DictReader(open("analysis/paper_panel.csv"))]
def f(x):
    try: return float(x)
    except: return None
S=[r for r in rows if str(r["rd_sample"])=="1" and r["purpose_class"]=="bond_go"
   and f(r["threshold_centered_margin"]) is not None]
for r in S: r["_m"]=f(r["threshold_centered_margin"])
M=[r["_m"] for r in S if r["_m"]!=0]
N=len(M)

BIN=0.5
def hist(lo,hi):
    c=Counter()
    for m in M:
        if lo<=m<hi: c[math.floor(m/BIN)]+=1
    return c
def density_fit(side,h):
    """local-linear fit of bin densities vs bin midpoints on one side; returns f0,var,nbins"""
    pts=[]
    c=hist(-h if side<0 else BIN*0, h if side>0 else 0) if False else None
    c=Counter()
    for m in M:
        b=math.floor(m/BIN)
        pts_range=(side<0 and -h<=m<0) or (side>0 and 0<m<=h)
        if pts_range: c[b]+=1
    pts=[((b+0.5)*BIN, cnt/(N*BIN)) for b,cnt in sorted(c.items())]
    S0=S1=S2=Sy=Smy=0.0
    for x,y in pts:
        w=1-abs(x)/h
        if w<=0: continue
        S0+=w; S1+=w*x; S2+=w*x*x; Sy+=w*y; Smy+=w*x*y
    det=S0*S2-S1*S1
    if det<=0: return None,None,len(pts)
    a=(S2*Sy-S1*Smy)/det; bcoef=(S0*Smy-S1*Sy)/det
    inv00,inv01=S2/det,-S1/det
    B00=B01=B11=0.0
    for x,y in pts:
        w=1-abs(x)/h
        if w<=0: continue
        e=y-a-bcoef*x; we2=(w*e)**2
        B00+=we2; B01+=we2*x; B11+=we2*x*x
    va=inv00*inv00*B00+2*inv00*inv01*B01+inv01*inv01*B11
    return a,va,len(pts)

L=["# Manipulation checks — McCrary density + donut-RD (rd_sample ∩ bond_go)\n",
   f"n = {N} (margin ≠ 0); bin width {BIN}pp. Generated by `mccrary_donut.py`.\n",
   "## 1 · McCrary log-density discontinuity",
   "| bandwidth h | f(0−) | f(0+) | θ = ln f+ − ln f− | SE(θ) | z |","|---|--:|--:|--:|--:|--:|"]
for h in (5,10,15):
    fl,vl,nl=density_fit(-1,h); fr,vr,nr=density_fit(+1,h)
    if not fl or not fr or fl<=0 or fr<=0: continue
    theta=math.log(fr)-math.log(fl)
    se=math.sqrt(vl/(fl*fl)+vr/(fr*fr))
    L.append(f"| {h}pp | {fl:.4f} | {fr:.4f} | {theta:+.3f} | {se:.3f} | {theta/se:.2f} |")
L.append("")

# ---- donut RD (reuse local-linear machinery) ----
def outcome(r,name):
    if name=="issued_6y": return float(r["issued_6y"]) if r["issued_6y"]!="" else None
    if name=="go_issue":
        if r["issued_6y"]=="":return None
        gs=f(r["go_share_6y"]); return 1.0 if (r["issued_6y"]=="1" and gs and gs>0) else 0.0
    return f(r.get(name))
def wls_side(data,bw,donut):
    pts=[(m,y) for m,y in data if donut<abs(m)<=bw]
    n=len(pts)
    if n<10: return None,None,n
    S0=S1=S2=Sy=Smy=0.0
    for m,y in pts:
        w=1-abs(m)/bw
        S0+=w; S1+=w*m; S2+=w*m*m; Sy+=w*y; Smy+=w*m*y
    det=S0*S2-S1*S1
    if det<=0: return None,None,n
    a=(S2*Sy-S1*Smy)/det; b=(S0*Smy-S1*Sy)/det
    inv00,inv01=S2/det,-S1/det
    B00=B01=B11=0.0
    for m,y in pts:
        w=1-abs(m)/bw; e=y-a-b*m; we2=(w*e)**2
        B00+=we2; B01+=we2*m; B11+=we2*m*m
    va=inv00*inv00*B00+2*inv00*inv01*B01+inv01*inv01*B11
    return a,va,n
def rd(dep,bw,donut):
    dl=[(r["_m"],outcome(r,dep)) for r in S if r["_m"]<0]
    dr=[(r["_m"],outcome(r,dep)) for r in S if r["_m"]>0]
    dl=[(m,y) for m,y in dl if y is not None]; dr=[(m,y) for m,y in dr if y is not None]
    aL,vL,nL=wls_side(dl,bw,donut); aR,vR,nR=wls_side(dr,bw,donut)
    if aL is None or aR is None: return None
    tau=aR-aL; se=math.sqrt(vL+vR)
    return tau,se,(tau/se if se>0 else 0),nL,nR

L+=["## 2 · Donut-RD (GO issuance ≤6y, bw ±10; exclude |margin| ≤ δ)",
    "| δ (donut) | τ | SE | z | n L/R |","|---|--:|--:|--:|---|"]
for donut in (0,0.5,1,2):
    res=rd("go_issue",10,donut)
    if res:
        tau,se,z,nL,nR=res
        L.append(f"| {donut}pp | {tau:+.3f} | {se:.3f} | {z:.2f} | {nL}/{nR} |")
L.append("")
L+=["## 2b · Donut-RD (any issuance ≤6y, bw ±10)","| δ | τ | SE | z | n L/R |","|---|--:|--:|--:|---|"]
for donut in (0,0.5,1,2):
    res=rd("issued_6y",10,donut)
    if res:
        tau,se,z,nL,nR=res
        L.append(f"| {donut}pp | {tau:+.3f} | {se:.3f} | {z:.2f} | {nL}/{nR} |")

open("analysis/MCCRARY_DONUT_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
