#!/usr/bin/env python3
"""Rows 9 + 13.

ENTITY MIDWIFERY (row 9): does refusal midwife NEW issuers in the same place?
For each rd_sample∩bond_go referendum: count units in the SAME COUNTY (GID
state+county digits; excluding the unit itself) whose FIRST-EVER EMMA issue
falls within 6y after the vote — all entrants, and special-district entrants
(type digit 4). RD (bw ±10) on 1(any entrant) and count.

INSTITUTIONAL WEDGE (row 13): the rule's effect at FIXED voter support.
 W2 (within CA, clean): support band 55–66.7 passes for schools (thr 55) but
 fails for non-schools (thr 66.7); band 50–55 fails for both. DiD:
 [sch−nonsch in 55–66.7] − [sch−nonsch in 50–55] on GO issuance ≤6y.
 W1 (cross-state): band 50–55 fails for CA schools, passes for TX/WI schools;
 band 55–60 passes for both. DiD: [CA−TXWI in 55–60] − [CA−TXWI in 50–55].
Writes analysis/MIDWIFERY_WEDGE_RESULTS.md."""
import csv, gzip, math, datetime as dt
from collections import defaultdict
import sys; sys.path.insert(0,"analysis")
from rdlib import rd

def f(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

# first-ever issue date per unit; county key = state2+county3 from GID
first={}
with gzip.open("analysis/cache/issuance_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        u=(r["pol_accountable_unit_id"] or "")[:9]
        d=pdate(r["dated_date"])
        if len(u)==9 and d and (u not in first or d<first[u]): first[u]=d
bycounty=defaultdict(list)
for u,d in first.items(): bycounty[u[:2]+u[3:6]].append((d,u))

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
S=[r for r in rows if str(r["rd_sample"])=="1" and r["purpose_class"]=="bond_go"
   and f(r["threshold_centered_margin"]) is not None]
for r in S:
    r["_m"]=f(r["threshold_centered_margin"])
    u=(r["unit_id"] or "")[:9]; d=pdate(r["election_date"])
    r["_ent"]=r["_entsp"]=None
    if len(u)==9 and d:
        n=nsp=0
        for fd,uu in bycounty.get(u[:2]+u[3:6],[]):
            if uu!=u and dt.timedelta(0)<fd-d<=dt.timedelta(days=2192):
                n+=1
                if uu[2]=="4": nsp+=1
        r["_ent"]=n; r["_entsp"]=nsp

L=["# Entity midwifery & the institutional wedge (rows 9, 13)\n","Generated by `midwifery_wedge.py`.\n",
   "## Row 9 · New issuers in the county within 6y (RD, bw ±10)",
   "| outcome | τ | SE | z | n L/R | left mean |","|---|--:|--:|--:|---|--:|"]
for lab,fn in [("1(any first-time issuer in county)",lambda r:(1.0 if r["_ent"] and r["_ent"]>0 else (0.0 if r["_ent"] is not None else None))),
               ("# first-time issuers",lambda r:float(r["_ent"]) if r["_ent"] is not None else None),
               ("# first-time SPECIAL-district issuers",lambda r:float(r["_entsp"]) if r["_entsp"] is not None else None)]:
    res=rd([(r["_m"],fn(r)) for r in S],10)
    if res: L.append(f"| {lab} | {res['tau']:+.3f} | {res['se']:.3f} | {res['z']:.2f} | {res['nL']}/{res['nR']} | {res['aL']:.3f} |")
L.append("\nSign read: NEGATIVE τ = more new entities appear after refusal (midwifery).\n")

# ---------- wedge ----------
def go(r):
    if r["issued_6y"]=="": return None
    gs=f(r["go_share_6y"]); return 1.0 if (r["issued_6y"]=="1" and gs and gs>0) else 0.0
def cellmean(rows_):
    v=[go(r) for r in rows_ if go(r) is not None]
    if len(v)<10: return None,len(v)
    m=sum(v)/len(v); return (m,len(v))
def se_p(m,n): return math.sqrt(m*(1-m)/n) if (m is not None and n>0) else None
ALL=[r for r in rows if r["purpose_class"]=="bond_go" and f(r["pct_yes"]) is not None and r["unit_id"]]
for r in ALL: r["_py"]=f(r["pct_yes"])
def band(rows_,lo,hi): return [r for r in rows_ if lo<=r["_py"]<hi]
L+=["## Row 13 · The institutional wedge — the rule at fixed voter support",
    "GO issuance ≤6y by support band; the rule flips pass/fail across columns.\n"]
# W2 within CA
casch=[r for r in ALL if r["state"]=="CA" and r["census_type"]=="school_district"]
cans=[r for r in ALL if r["state"]=="CA" and r["census_type"]!="school_district"]
L+=["### W2 · Within CA: schools (thr 55) vs non-schools (thr 66.7)",
    "| support band | schools (rule: see band) | non-schools (fail both bands) |","|---|--:|--:|"]
cells={}
for blab,lo,hi in [("50–55 (both FAIL)",50,55),("55–66.7 (schools PASS, non-schools FAIL)",55,66.7)]:
    m1,n1=cellmean(band(casch,lo,hi)); m2,n2=cellmean(band(cans,lo,hi))
    cells[(blab,"s")]=(m1,n1); cells[(blab,"n")]=(m2,n2)
    L.append(f"| {blab} | {m1:.1%} (n={n1}) | {m2:.1%} (n={n2}) |")
try:
    d1=cells[("55–66.7 (schools PASS, non-schools FAIL)","s")][0]-cells[("55–66.7 (schools PASS, non-schools FAIL)","n")][0]
    d0=cells[("50–55 (both FAIL)","s")][0]-cells[("50–55 (both FAIL)","n")][0]
    var=sum(se_p(*cells[k])**2 for k in cells)
    L.append(f"\n**W2 DiD (rule effect at fixed support): {d1-d0:+.3f} (SE≈{math.sqrt(var):.3f})**\n")
except Exception as e:
    L.append(f"\nW2 DiD not computable: {e}\n")
# W1 cross-state schools
txwi=[r for r in ALL if r["state"] in ("TX","WI") and r["census_type"]=="school_district"]
L+=["### W1 · Schools across states: CA (thr 55) vs TX+WI (thr 50)",
    "| support band | CA schools | TX+WI schools |","|---|--:|--:|"]
cells={}
for blab,lo,hi in [("50–55 (CA FAIL, TX/WI PASS)",50,55),("55–60 (both PASS)",55,60)]:
    m1,n1=cellmean(band(casch,lo,hi)); m2,n2=cellmean(band(txwi,lo,hi))
    cells[(blab,"c")]=(m1,n1); cells[(blab,"t")]=(m2,n2)
    L.append(f"| {blab} | {m1:.1%} (n={n1}) | {m2:.1%} (n={n2}) |")
try:
    d1=cells[("55–60 (both PASS)","c")][0]-cells[("55–60 (both PASS)","t")][0]
    d0=cells[("50–55 (CA FAIL, TX/WI PASS)","c")][0]-cells[("50–55 (CA FAIL, TX/WI PASS)","t")][0]
    var=sum(se_p(*cells[k])**2 for k in cells)
    L.append(f"\n**W1 DiD (rule effect at fixed support): {d1-d0:+.3f} (SE≈{math.sqrt(var):.3f})**")
except Exception as e:
    L.append(f"\nW1 DiD not computable: {e}")
open("analysis/MIDWIFERY_WEDGE_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
