#!/usr/bin/env python3
"""P2 — the cumulative wedge (round-2, Tier 2).

Frame: rd_sample ∩ bond_go, |threshold-centered margin| ≤ 5 (the causal margin),
election date + unit present. Curves by relative year k = −2..+6:
  A  share of measures with ≥1 new-money issue in [−2, k]   (per side)
  B  mean cumulative new-money par per capita over [−2, k]  (per side; pop =
     gfd_pop, enrollment fallback; rows without a denominator drop from B only)
New-money = has_new_money & !has_refunding, deduped to one doc per issue_id.
Abstract numbers: median time-to-first-issue among ≤6y issuers per side (the
delay); never-issued-by-+6 share per side; fate-table 18.2% reconciliation.
Writes analysis/P2_RESULTS.md + analysis/fig_cumulative_wedge.svg
(palette validated: #2a78d6 passed / #eb6834 failed on white, all checks PASS)."""
import csv, gzip, datetime as dt
from collections import defaultdict

def f(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

# unit -> [(date, issue_key, par)] new-money, deduped
iss=defaultdict(list); seen=set()
with gzip.open("analysis/cache/issuance_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        d=pdate(r["dated_date"])
        if not d: continue
        nm=(r.get("has_new_money","").lower() in ("true","1")) and (r.get("has_refunding","").lower() not in ("true","1"))
        if not nm: continue
        key=r["issue_id"] or r["doc_id"]
        if key in seen: continue
        seen.add(key)
        iss[(r["pol_accountable_unit_id"] or "")[:9]].append((d,f(r["par_effective"]) or 0.0))

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
S=[]
for r in rows:
    if str(r["rd_sample"])!="1" or r["purpose_class"]!="bond_go": continue
    m=f(r["threshold_centered_margin"]); d=pdate(r["election_date"])
    if m is None or not d or not r["unit_id"] or abs(m)>5 or m==0: continue
    pop=f(r["gfd_pop"])
    if not pop or pop<=0: pop=f(r["gfd_enrollment"])
    ev=[]
    for dd,par in iss.get(r["unit_id"][:9],[]):
        rel=(dd-d).days/365.25
        if -2<=rel<=6.0: ev.append((rel,par))
    S.append(dict(side="passed" if m>0 else "failed",ev=sorted(ev),pop=pop))
KS=list(range(-2,7))
curveA={}; curveB={}; nside={}
for side in ("passed","failed"):
    G=[s for s in S if s["side"]==side]; nside[side]=len(G)
    A=[]; B=[]
    GB=[s for s in G if s["pop"]]
    for k in KS:
        A.append(sum(1 for s in G if any(rel<k+1 for rel,_ in s["ev"]))/len(G))
        B.append(sum(sum(p for rel,p in s["ev"] if rel<k+1)/s["pop"] for s in GB)/len(GB))
    curveA[side]=A; curveB[side]=B

def med(v):
    v=sorted(v); return v[len(v)//2] if v else None
delay={}
for side in ("passed","failed"):
    t=[min(rel for rel,_ in s["ev"] if rel>=0) for s in S
       if s["side"]==side and any(rel>=0 for rel,_ in s["ev"])]
    delay[side]=med(t)
never={side:1-curveA[side][-1] for side in ("passed","failed")}
# year at which failed cumulative share reaches passed's end-of-year-0 level
target=curveA["passed"][KS.index(0)]
reach=next((k for k in KS if curveA["failed"][KS.index(k)]>=target),None)

L=["# P2 — the cumulative wedge (|margin| ≤ 5)\n",
   f"Generated by `p2_cumulative_wedge.py`. Measures: barely-passed {nside['passed']}, "
   f"barely-failed {nside['failed']}. Figure: `fig_cumulative_wedge.svg`.\n",
   "## Cumulative share with ≥1 new-money issue since k=−2",
   "| k | "+" | ".join(str(k) for k in KS)+" |","|---|"+"--:|"*len(KS)]
for side in ("passed","failed"):
    L.append(f"| {side} | "+" | ".join(f"{v:.3f}" for v in curveA[side])+" |")
L+=["","## Mean cumulative new-money par per capita ($) since k=−2",
    "| k | "+" | ".join(str(k) for k in KS)+" |","|---|"+"--:|"*len(KS)]
for side in ("passed","failed"):
    L.append(f"| {side} | "+" | ".join(f"{v:,.0f}" for v in curveB[side])+" |")
L+=["","## The abstract numbers",
    f"- Median time to FIRST post-vote new-money issue (among ≤6y issuers): "
    f"passed **{delay['passed']:.2f}y**, failed **{delay['failed']:.2f}y** → "
    f"**median delay ≈ {delay['failed']-delay['passed']:.2f} years**.",
    f"- The barely-failed side reaches the barely-passed side's end-of-year-0 level "
    f"({target:.3f}) {'in year **'+str(reach)+'**' if reach is not None else '**never within +6**'} — "
    f"a horizontal wedge of ≈{reach} years." if reach is not None else
    f"- The barely-failed side NEVER reaches the passed side's year-0 level ({target:.3f}) within +6.",
    f"- Never issued by +6: passed **{never['passed']:.1%}**, failed **{never['failed']:.1%}** — "
    f"vertical wedge **{never['failed']-never['passed']:+.1%}**.",
    f"- Fate-table reconciliation: the failed side's {never['failed']:.1%} no-issue share",
    f"  decomposes (TRANSITION_FATE, 2005–19 cohort) into extinguished-with-no-return",
    f"  (18.2%) plus returned-but-unconverted-and-unissued; the curves here use the",
    f"  full close frame (all years), the fate table the 2005–19 full-window cohort —",
    f"  frame difference stated, not reconciled away.",""]

# ---------- figure ----------
BLUE="#2a78d6"; ORANGE="#eb6834"; INK="#0b0b0b"; SEC="#52514e"; GRID="#e7e6e3"
W,H=980,400; PW,PH=380,270; X0=[70,560]; Y0=60
def sx(p,k): return X0[p]+(k+2)/8*PW
def sy_a(v): return Y0+PH-(v*PH)
import math as _math
bmax=_math.ceil(max(max(curveB["passed"]),max(curveB["failed"]))*1.05/2000)*2000
def sy_b(v): return Y0+PH-(v/bmax*PH)
S_=[f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" font-family="Helvetica,Arial,sans-serif">',
    f'<rect width="{W}" height="{H}" fill="#ffffff"/>',
    f'<text x="{X0[0]}" y="26" font-size="15" font-weight="bold" fill="{INK}">The cumulative wedge: barely-authorized vs barely-refused (|margin| ≤ 5)</text>',
    f'<text x="{X0[0]}" y="44" font-size="11.5" fill="{SEC}">Left: share with ≥1 new-money issue since k=−2 · Right: mean cumulative new-money par per capita ($)</text>',
    # legend
    f'<circle cx="{X0[1]+120}" cy="22" r="4.5" fill="{BLUE}"/><text x="{X0[1]+130}" y="26" font-size="11.5" fill="{SEC}">barely passed</text>',
    f'<circle cx="{X0[1]+225}" cy="22" r="4.5" fill="{ORANGE}"/><text x="{X0[1]+235}" y="26" font-size="11.5" fill="{SEC}">barely failed</text>']
for p,(curve,sy,fmt,ylab) in enumerate([(curveA,sy_a,lambda v:f"{v:.2f}","share ever issued"),
                                        (curveB,sy_b,lambda v:f"${v:,.0f}","cumulative par per capita")]):
    # grid + y labels
    for i in range(5):
        vv=i/4
        yy=Y0+PH-vv*PH
        val=vv if p==0 else vv*bmax
        S_.append(f'<line x1="{X0[p]}" y1="{yy:.1f}" x2="{X0[p]+PW}" y2="{yy:.1f}" stroke="{GRID}" stroke-width="1"/>')
        S_.append(f'<text x="{X0[p]-8}" y="{yy+4:.1f}" font-size="10.5" fill="{SEC}" text-anchor="end">{fmt(val) if p==1 else f"{val:.2f}"}</text>')
    # x axis
    for k in KS:
        xx=sx(p,k)
        S_.append(f'<text x="{xx:.1f}" y="{Y0+PH+18}" font-size="10.5" fill="{SEC}" text-anchor="middle">{k:+d}</text>')
    S_.append(f'<text x="{X0[p]+PW/2}" y="{Y0+PH+38}" font-size="11" fill="{SEC}" text-anchor="middle">years since the vote</text>')
    # vote line
    xv=sx(p,0)
    S_.append(f'<line x1="{xv:.1f}" y1="{Y0}" x2="{xv:.1f}" y2="{Y0+PH}" stroke="{SEC}" stroke-width="1" stroke-dasharray="3,3"/>')
    S_.append(f'<text x="{xv+4:.1f}" y="{Y0+12}" font-size="10" fill="{SEC}">vote</text>')
    for side,col in (("passed",BLUE),("failed",ORANGE)):
        pts=" ".join(f"{sx(p,k):.1f},{sy(curve[side][i]):.1f}" for i,k in enumerate(KS))
        S_.append(f'<polyline points="{pts}" fill="none" stroke="{col}" stroke-width="2"/>')
        xe,ye=sx(p,6),sy(curve[side][-1])
        S_.append(f'<circle cx="{xe:.1f}" cy="{ye:.1f}" r="3.5" fill="{col}"/>')
        S_.append(f'<text x="{xe+7:.1f}" y="{ye+4:.1f}" font-size="10.5" fill="{INK}">{fmt(curve[side][-1])}</text>')
S_.append("</svg>")
open("analysis/fig_cumulative_wedge.svg","w").write("\n".join(S_))
open("analysis/P2_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
print("wrote analysis/fig_cumulative_wedge.svg")
