#!/usr/bin/env python3
"""P3 — the F6 residual: is majority-failures' lower 6y issuance a truncation
artifact? (round-2, Tier 2)

Puzzle (FAILURE_PATHS): within CA, majority-failures (50<yes<thr) RE-SUBMIT more
(42.2% vs 27.4%) yet show LOWER any-issuance ≤6y (23.5% vs 34.6%). If recovery
runs vote→return (~1–2y)→pass→issue, a 6y window truncates the re-vote channel
specifically. Tests, within CA failed bond_go (per-measure threshold):
  T1  cumulative any new-money issuance by k = 1..8 years since failure,
      majority- vs minority-failures (calendar-observability-restricted per k:
      only failures with ≥k years of issuance data enter the year-k cell)
  T2  the same, CA schools only (regime × purpose held fixed, thr 55)
  T3  channel of the FIRST post-failure issue (voter / council+statutory) by
      group — does the majority-failure recovery ride the re-vote channel?
  T4  time from failure to first PASSED return, and from that pass to first
      issue (medians), by group.
Writes analysis/P3_RESULTS.md."""
import csv, gzip, datetime as dt
from collections import defaultdict

def f(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

# new-money issues per unit (deduped), with auth mode
iss=defaultdict(list); seen=set(); maxd=dt.date(1900,1,1)
with gzip.open("analysis/cache/issuance_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        d=pdate(r["dated_date"])
        if not d: continue
        if d>maxd: maxd=d
        nm=(r.get("has_new_money","").lower() in ("true","1")) and (r.get("has_refunding","").lower() not in ("true","1"))
        if not nm: continue
        key=r["issue_id"] or r["doc_id"]
        if key in seen: continue
        seen.add(key)
        am=r.get("auth_mode_final2") or ""
        iss[(r["pol_accountable_unit_id"] or "")[:9]].append((d,am))
for k in iss: iss[k].sort()

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
seq=defaultdict(list)
for r in rows:
    d=pdate(r["election_date"])
    if r["unit_id"] and d: seq[(r["unit_id"],r["purpose_class"])].append((d,r["passed"]))
for k in seq: seq[k].sort()

CA=[]
for r in rows:
    if r["state"]!="CA" or r["purpose_class"]!="bond_go" or r["passed"]!="0": continue
    py=f(r["pct_yes"]); m=f(r["threshold_centered_margin"]); d=pdate(r["election_date"])
    if py is None or m is None or not d or not r["unit_id"]: continue
    thr=round(py-m,1)
    grp="maj" if 50<py<thr else ("min" if py<50 else None)
    if not grp: continue
    CA.append(dict(r=r,d=d,grp=grp,school=r["census_type"]=="school_district"))

def cum_table(sample,title):
    out=[f"### {title}","| years since failure k | maj-fail issued ≤k (n at risk) | min-fail issued ≤k (n) | gap |","|---|--:|--:|--:|"]
    for k in range(1,9):
        cell={}
        for g in ("maj","min"):
            G=[x for x in sample if x["grp"]==g and (maxd-x["d"]).days>=k*365.25]
            if len(G)<15: cell[g]=(None,len(G)); continue
            hit=sum(1 for x in G if any(dt.timedelta(0)<dd-x["d"]<=dt.timedelta(days=int(k*365.25))
                                        for dd,_ in iss.get((x["r"]["unit_id"] or "")[:9],[])))
            cell[g]=(hit/len(G),len(G))
        a,na=cell["maj"]; b,nb=cell["min"]
        if a is None or b is None:
            out.append(f"| {k} | – (n={na}) | – (n={nb}) | – |")
        else:
            out.append(f"| {k} | {a:.1%} (n={na}) | {b:.1%} (n={nb}) | {a-b:+.1%} |")
    return out

L=["# P3 — F6 residual: truncation test on the majority-failure issuance gap\n",
   f"Generated by `p3_f6_truncation.py`. CA failed GO-bond measures with margin: "
   f"maj {sum(1 for x in CA if x['grp']=='maj')}, min {sum(1 for x in CA if x['grp']=='min')}. "
   f"Issuance data horizon: {maxd.isoformat()}.\n",
   "## T1 · Cumulative any new-money issuance since failure (all CA)"]
L+=cum_table(CA,"All CA failed bond_go")
L+=["","## T2 · CA schools only (thr 55 — regime × purpose fixed)"]
L+=cum_table([x for x in CA if x["school"]],"CA school failures")

# T3 channel of first post-failure issue (within 8y)
L+=["","## T3 · Channel of FIRST post-failure new-money issue (≤8y, obs-restricted)",
    "| group | n obs≥8y | voter | council/statutory | other | none ≤8y |","|---|--:|--:|--:|--:|--:|"]
for g in ("maj","min"):
    G=[x for x in CA if x["grp"]==g and (maxd-x["d"]).days>=8*365.25]
    n=len(G); c=defaultdict(int)
    for x in G:
        first=None
        for dd,am in iss.get((x["r"]["unit_id"] or "")[:9],[]):
            if dt.timedelta(0)<dd-x["d"]<=dt.timedelta(days=int(8*365.25)):
                first=am; break
        if first is None: c["none"]+=1
        elif first=="voter": c["voter"]+=1
        elif first in ("council_or_board","statutory"): c["council"]+=1
        else: c["other"]+=1
    L.append(f"| {g} | {n} | {c['voter']/n:.1%} | {c['council']/n:.1%} | {c['other']/n:.1%} | {c['none']/n:.1%} |")

# T4 timing chain: failure -> first passed return -> first issue after that pass
L+=["","## T4 · The re-vote chain (medians)","| group | n w/ passed return ≤4y | fail→passed return (y) | pass→first issue (y) | total fail→issue (y) |","|---|--:|--:|--:|--:|"]
def med(v):
    v=sorted(v); return v[len(v)//2] if v else None
for g in ("maj","min"):
    t1s=[];t2s=[];t3s=[]
    for x in CA:
        if x["grp"]!=g: continue
        pr=None
        for dj,pj in seq[(x["r"]["unit_id"],"bond_go")]:
            if dj>x["d"] and (dj-x["d"]).days<=1461 and pj=="1": pr=dj; break
        if not pr: continue
        fi=None
        for dd,_ in iss.get((x["r"]["unit_id"] or "")[:9],[]):
            if dd>pr: fi=dd; break
        t1s.append((pr-x["d"]).days/365.25)
        if fi:
            t2s.append((fi-pr).days/365.25); t3s.append((fi-x["d"]).days/365.25)
    m1,m2,m3=med(t1s),med(t2s),med(t3s)
    L.append(f"| {g} | {len(t1s)} | {m1:.2f} | {m2:.2f} (n={len(t2s)}) | {m3:.2f} |" if m2 else f"| {g} | {len(t1s)} | – | – | – |")
L+=["","Note: T1/T2 count NEW-MONEY issues only (the FAILURE_PATHS `issued_6y` levels are",
    "higher because that flag includes refundings) — levels differ, the contrast is the object.",
    "","## Adjudication",
    "1. **Truncation is REFUTED as the explanation.** The majority-failure issuance",
    "   deficit does not close with a longer window — it WIDENS: all-CA gap −5.3pp at",
    "   6y → −6.4pp at 8y; CA schools −6.7pp → −8.0pp, with the at-risk set held to",
    "   ≥k years of issuance observability in every cell. Genuinely lower, not an",
    "   artifact of the 6y horizon.",
    "2. **The mechanism lead is in the chain (T4):** majority-failures CONVERT more",
    "   (107 passed returns ≤4y vs 25) but the conversions sit unissued — median",
    "   pass→first-issue 6.21y vs 2.93y for minority-failures, and only 5.5% of",
    "   maj-failures see a voter-mode first issue within 8y (T3) vs 13.5%. The",
    "   near-miss signature is RE-APPROVED BUT UNISSUED: authorization re-assembled,",
    "   drawdown deferred beyond the horizon.",
    "3. F6's open puzzle is therefore reframed, not closed: the deficit is real at",
    "   8y; whether the banked re-authorizations eventually issue (10y+) is left to",
    f"   a longer-horizon pass. Conditional pass→issue medians ride small n — direction, not magnitude."]
open("analysis/P3_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
