#!/usr/bin/env python3
"""P4 — the banked-authorisation mechanism: does the rate cap meter drawdown?

The P3 fact: CA near-miss failures convert by re-vote but sit unissued
(median pass→first-issue 6.2y). Candidate mechanism: Proposition 39
authorisations (55% threshold) carry statutory TAX-RATE CAPS ($30/$60/$25 per
$100k AV by district type) that meter how fast authorised bonds can be sold;
traditional two-thirds authorisations carry no cap.

Test: CA failed bond_go measures with a same-unit PASSED return ≤4y. Classify
the RETURN's regime from its per-measure threshold (55 = capped Prop-39 route;
66.7 = uncapped traditional route). Compare pass→first-issue timing and
issuance within 6y of the pass / 8y of the failure.
  Split A (clean): WITHIN SCHOOL DISTRICTS, 55-returns vs 66.7-returns —
    districts choose the route, so selection into route is flagged.
  Split B (confounded, flagged): schools-55 vs non-school-66.7 — regime
    coincides with entity class in CA.
Supplementary: among capped school conversions, deferral vs pre-vote property-
tax-per-capita (a WEAK AV-headroom proxy — county rolls not in repo; flagged).
Writes analysis/P4_RESULTS.md."""
import csv, gzip, math, datetime as dt
from collections import defaultdict

def f(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

iss=defaultdict(list); seen=set(); maxd=dt.date(1900,1,1)
with gzip.open("analysis/cache/issuance_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        d=pdate(r["dated_date"])
        if not d: continue
        if d>maxd: maxd=d
        nm=(r.get("has_new_money","").lower() in ("true","1")) and (r.get("has_refunding","").lower() not in ("true","1"))
        if not nm: continue
        k=r["issue_id"] or r["doc_id"]
        if k in seen: continue
        seen.add(k)
        iss[(r["pol_accountable_unit_id"] or "")[:9]].append(d)
for k in iss: iss[k].sort()

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
seq=defaultdict(list)
for r in rows:
    d=pdate(r["election_date"])
    if r["unit_id"] and d and r["purpose_class"]=="bond_go":
        seq[r["unit_id"]].append((d,r))
for k in seq: seq[k].sort(key=lambda x:x[0])

CONV=[]
for r in rows:
    if r["state"]!="CA" or r["purpose_class"]!="bond_go" or r["passed"]!="0": continue
    d=pdate(r["election_date"])
    py,m=f(r["pct_yes"]),f(r["threshold_centered_margin"])
    if not d or not r["unit_id"] or py is None: continue
    ret=None
    for dj,rj in seq[r["unit_id"]]:
        if dj>d and (dj-d).days<=1461 and rj["passed"]=="1":
            ret=(dj,rj); break
    if not ret: continue
    dj,rj=ret
    pyj,mj=f(rj["pct_yes"]),f(rj["threshold_centered_margin"])
    if pyj is None or mj is None: continue
    thr=round(pyj-mj,1)
    regime="capped55" if abs(thr-55)<1 else ("uncapped667" if abs(thr-66.7)<1 else None)
    if regime is None: continue
    u=r["unit_id"][:9]
    fi=next((dd for dd in iss.get(u,[]) if dd>dj),None)
    t_issue=(fi-dj).days/365.25 if fi else None
    obs_pass=(maxd-dj).days/365.25
    iss6=(1 if (fi and t_issue<=6) else (0 if obs_pass>=6 else None))
    obs_fail=(maxd-d).days/365.25
    iss8=(1 if any(dt.timedelta(0)<dd-d<=dt.timedelta(days=int(8*365.25)) for dd in iss.get(u,[]))
          else (0 if obs_fail>=8 else None))
    ptx=f(r["gfd_property_tax"]); pop=f(r["gfd_pop"])
    CONV.append(dict(regime=regime,school=r["census_type"]=="school_district",
                     t=t_issue,iss6=iss6,iss8=iss8,
                     ptxpc=(ptx*1000/pop if ptx and pop and pop>0 else None)))
def med(v):
    v=sorted(v); return v[len(v)//2] if v else None
def cell(G):
    ts=[c["t"] for c in G if c["t"] is not None]
    i6=[c["iss6"] for c in G if c["iss6"] is not None]
    i8=[c["iss8"] for c in G if c["iss8"] is not None]
    return (len(G),med(ts),len(ts),
            (sum(i6)/len(i6) if i6 else None),len(i6),
            (sum(i8)/len(i8) if i8 else None),len(i8))
L=["# P4 — the rate-cap split: is the cap metering banked authorisations?\n",
   f"Generated by `p4_rate_cap.py`. CA failed GO measures with a passed return ≤4y,",
   f"return regime classifiable: **{len(CONV)}** conversions "
   f"(capped-55: {sum(1 for c in CONV if c['regime']=='capped55')}, "
   f"uncapped-66.7: {sum(1 for c in CONV if c['regime']=='uncapped667')}). "
   f"Issuance horizon {maxd.isoformat()}.\n",
   "| split | group | conversions | median pass→first issue (y, n) | issued ≤6y of pass (n) | issued ≤8y of failure (n) |",
   "|---|---|--:|--:|--:|--:|"]
A=[c for c in CONV if c["school"]]
for lab,G in [("A · within schools (route choice — selection flagged)",None),
              ("", [c for c in A if c["regime"]=="capped55"]),
              (" ", [c for c in A if c["regime"]=="uncapped667"]),
              ("B · cross-class (regime ⊥̸ entity — CONFOUNDED, flagged)",None),
              ("  ",[c for c in CONV if c["school"] and c["regime"]=="capped55"]),
              ("   ",[c for c in CONV if not c["school"] and c["regime"]=="uncapped667"])]:
    if G is None:
        L.append(f"| **{lab}** | | | | | |"); continue
    n,mt,nt,i6,n6,i8,n8=cell(G)
    nm={"":"schools, 55% return (rate-capped)"," ":"schools, 66.7% return (uncapped)",
        "  ":"schools (capped 55)","   ":"non-schools (uncapped 66.7)"}[lab]
    L.append(f"| | {nm} | {n} | {mt:.2f} ({nt}) | {f'{i6:.1%} ({n6})' if i6 is not None else '–'} | {f'{i8:.1%} ({n8})' if i8 is not None else '–'} |"
             if mt is not None else f"| | {nm} | {n} | – | – | – |")
cap=[c for c in A if c["regime"]=="capped55" and c["t"] is not None and c["ptxpc"]]
if len(cap)>=20:
    cap.sort(key=lambda c:c["ptxpc"])
    lo=cap[:len(cap)//2]; hi=cap[len(cap)//2:]
    L+=["","## Supplementary: deferral vs fiscal-base proxy (capped school conversions)",
        f"Pre-vote property tax per capita as a WEAK AV-headroom proxy (county assessed-",
        f"value rolls not in repo — flagged): median pass→first-issue **{med([c['t'] for c in lo]):.2f}y**",
        f"below-median base (n={len(lo)}) vs **{med([c['t'] for c in hi]):.2f}y** above-median (n={len(hi)}).",
        "Prediction if the cap meters drawdown: LOW-base (low headroom) districts defer longer."]
else:
    L+=["","Supplementary headroom split: insufficient n with both timing and tax base."]
L+=["","## Reading rules","- Split A is the test: same entity class, route chosen by the district —",
    "  route SELECTION is the caveat (districts expecting slow drawdown may choose 55%).",
    "- Split B is reported for completeness and is confounded with everything the",
    "  chargeability fork says about entity classes — do not cite it as the mechanism.",
    "- Verdict written to FINDINGS after the numbers above.",
    "","## Verdict: NOT CONFIRMED — the fact stands unexplained",
    "The uncapped-route cell is too thin to test (9 school conversions, 8 with",
    "timing), and its point direction runs AGAINST the cap story (median 9.74y",
    "to first issue vs 4.93y for capped conversions). The rate-cap mechanism is",
    "neither supported nor excluded at this n; the AV-headroom proxy lacks joint",
    "coverage. Per instruction, 're-approved but unissued' remains a documented",
    "fact without an adjudicated mechanism. Upgrade path: county assessed-value",
    "rolls (headroom directly) and the CDIAC sold-vs-authorised series."]
open("analysis/P4_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
