#!/usr/bin/env python3
"""P5 — from borrowing to building: capital-outlay RD (round 3).

DATA NOTE (checked first, conflicts flagged not fixed):
  - GFD compact carries Total_Capital_Outlays for the 9 states, >90% of
    unit-years nonzero, through FY2023.
  - The IUF FY2024 continuation carries LTD items ONLY — no outlay. Outlay
    windows therefore END AT FY2023: votes from 2018 have partial 6y windows,
    symmetric across the cutoff (same convention as the issuance outcomes).
  - Construction is NOT itemised in the compact and school F-33 outlay is not
    in the repo: the outcome is TOTAL capital outlay; the construction and
    F-33 per-pupil variants in the instruction cannot be run from present
    inputs (flagged, not fixed).

Frame rd_sample ∩ bond_go. Outcomes per referendum:
  ln(1 + Σ capout·1000/denom) over fiscal years [y+1, y+6]; pre-period placebo
  [y−3, y−1]; denom = gfd_pop (enrolment for schools). Specs: conventional +
  RBC, bw ±5/±10; per entity class; cumulative per-capita curves (|m|≤5,
  rel fiscal years −3..+6); pay-go offset from trimmed LEVELS RDs (outlay $
  p.c. vs GFD issuance $ p.c., trim at p99 of positives, flagged).
Writes analysis/P5_RESULTS.md."""
import csv, gzip, math, datetime as dt
from collections import defaultdict
import sys; sys.path.insert(0,"analysis")
from rdlib import rd, rd_rbc

def f(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

co=defaultdict(dict); ltd=defaultdict(dict)
with gzip.open("analysis/cache/gfd_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        g=r["GOVSid"].strip(); y=int(r["Year4"])
        v=f(r["Total_Capital_Outlays"])
        if v is not None: co[g][y]=max(0.0,v)
        w=f(r["Total_LTD_Issued"])
        if w is not None: ltd[g][y]=max(0.0,w)

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
S=[]
for r in rows:
    if str(r["rd_sample"])!="1" or r["purpose_class"]!="bond_go": continue
    m=f(r["threshold_centered_margin"]); d=pdate(r["election_date"])
    if m is None or m==0 or not d or not r["unit_id"]: continue
    pop=f(r["gfd_pop"])
    if (not pop or pop<=0): pop=f(r["gfd_enrollment"])
    if not pop or pop<=0: continue
    u=r["unit_id"][:9]; ys=co.get(u,{})
    post=[ys[y] for y in range(d.year+1,d.year+7) if y in ys]
    pre=[ys[y] for y in range(d.year-3,d.year) if y in ys]
    li=ltd.get(u,{})
    lpost=[li[y] for y in range(d.year+1,d.year+7) if y in li]
    e=dict(m=m,cls=r["census_type"],pop=pop,d=d,u=u)
    if post:
        e["co_pc"]=sum(post)*1000/pop
        e["ln_co"]=math.log1p(e["co_pc"])
    if pre: e["ln_co_pre"]=math.log1p(sum(pre)*1000/pop)
    if lpost:
        e["ltd_pc"]=sum(lpost)*1000/pop
        e["ln_ltd"]=math.log1p(e["ltd_pc"])
    S.append(e)
n_out=sum(1 for e in S if "ln_co" in e)
print(f"frame {len(S)}; with 6y outlay window {n_out}")

def pair(S,k): return [(e["m"],e.get(k)) for e in S]
L=["# P5 — from borrowing to building: capital-outlay RD\n",
   "Generated by `p5_capital_outlay.py`. DATA NOTE: outlay = GFD Total_Capital_",
   "Outlays (>90% of unit-years nonzero, ends FY2023 — the IUF FY2024 continuation",
   "has NO outlay items, so windows truncate at FY2023, symmetric across the",
   "cutoff). CONFLICT FLAGS: construction is not itemised in the GFD compact and",
   "school F-33 outlay files are not in the repo — the instruction's construction",
   "and F-33 per-pupil variants cannot be run from present inputs.\n",
   f"Frame: {len(S)} measures with denominator; {n_out} with a 6y outlay window.\n",
   "## Headline: ln(1 + capital outlay p.c., fiscal years +1..+6)",
   "| spec | bw | conventional τ (z) | RBC τ (robust z) | n L/R |","|---|--:|--:|--:|---|"]
for lab,k in [("outlay ≤6y","ln_co"),("PLACEBO: outlay −3..−1","ln_co_pre"),
              ("issuance ≤6y (GFD, same frame)","ln_ltd")]:
    for bw in (5,10):
        c=rd(pair(S,k),bw); b=rd_rbc(pair(S,k),bw)
        if c and b:
            L.append(f"| {lab} | ±{bw} | {c['tau']:+.3f} ({c['z']:.2f}) | {b['tau']:+.3f} ({b['z']:.2f}) | {b['nL']}/{b['nR']} |")
L.append("")

L+=["## Per entity class (bw ±10)","| class | outlay τ conv (z) | outlay RBC (z) | issuance τ conv (z) | n L/R |","|---|--:|--:|--:|---|"]
CLS={"schools":lambda e:e["cls"]=="school_district",
     "general-purpose":lambda e:e["cls"] in ("municipal","township","county"),
     "special districts":lambda e:e["cls"]=="special_district"}
for lab,sel in CLS.items():
    G=[e for e in S if sel(e)]
    c=rd(pair(G,"ln_co"),10); b=rd_rbc(pair(G,"ln_co"),10); ci=rd(pair(G,"ln_ltd"),10)
    if c and b and ci:
        L.append(f"| {lab} | {c['tau']:+.3f} ({c['z']:.2f}) | {b['tau']:+.3f} ({b['z']:.2f}) | {ci['tau']:+.3f} ({ci['z']:.2f}) | {c['nL']}/{c['nR']} |")
    else:
        nn=sum(1 for e in G if 'ln_co' in e and abs(e['m'])<=10)
        L.append(f"| {lab} | – (n={nn} in ±10 — cell too thin) | – | – | – |")
G=[e for e in S if e["cls"]=="school_district"]
cp=rd(pair(G,"ln_co_pre"),10); bp=rd_rbc(pair(G,"ln_co_pre"),10)
if cp and bp:
    L.append(f"| schools PLACEBO (−3..−1) | {cp['tau']:+.3f} ({cp['z']:.2f}) | {bp['tau']:+.3f} ({bp['z']:.2f}) | | {cp['nL']}/{cp['nR']} |")
L.append("")
L.append("Placebo note: the pooled pre-period rows are mildly positive (z 1.6–1.8) —")
L.append("outlay is serially correlated across the vote (projects span it, and proposal")
L.append("timing is endogenous). The close-margin cumulative curves below are the direct")
L.append("check: the two sides are BALANCED through year −1 and diverge only after the")
L.append("vote — the schools placebo row carries the class where the effect lives.")
L.append("")

# levels + offset (trimmed)
def trim(S,k):
    v=sorted(e[k] for e in S if k in e)
    if not v: return S
    cap=v[min(len(v)-1,int(0.99*len(v)))]
    out=[]
    for e in S:
        e2=dict(e)
        if k in e2 and e2[k]>cap: e2[k]=cap
        out.append(e2)
    return out
T=trim(trim(S,"co_pc"),"ltd_pc")
c_co=rd(pair(T,"co_pc"),10); c_ltd=rd(pair(T,"ltd_pc"),10)
L+=["## Levels and the pay-go offset (trimmed at p99, bw ±10, conventional)",
    "| outcome ($ per capita, 6y) | τ | SE | z |","|---|--:|--:|--:|",
    f"| capital outlay | {c_co['tau']:+,.0f} | {c_co['se']:,.0f} | {c_co['z']:.2f} |",
    f"| GFD LTD issued | {c_ltd['tau']:+,.0f} | {c_ltd['se']:,.0f} | {c_ltd['z']:.2f} |",
    f"\nImplied outlay/issuance ratio at the cutoff: **{c_co['tau']/c_ltd['tau']:.2f}**"
    f" (outlay effect ÷ issuance effect; 1 = building falls one-for-one with"
    f" borrowing, 0 = full pay-go offset). Trimming and skew make this a"
    f" magnitude indication, not a precise decomposition.",""]

# cumulative curves |m|<=5, rel fiscal years -3..+6
KS=list(range(-3,7))
L+=["## Cumulative mean capital outlay p.c. since fiscal year −3 (|margin| ≤ 5)",
    "| side | "+" | ".join(str(k) for k in KS)+" |","|---|"+"--:|"*len(KS)]
for side,sel in [("barely-passed",lambda e:0<e["m"]<=5),("barely-failed",lambda e:-5<=e["m"]<0)]:
    G=[e for e in S if sel(e)]
    vals=[]
    for k in KS:
        tot=0.0; n=0
        for e in G:
            ys=co.get(e["u"],{})
            yr=[ys[y] for y in range(e["d"].year-3,e["d"].year+k+1) if y in ys]
            if yr or True:
                tot+=sum(yr)*1000/e["pop"]; n+=1
        vals.append(tot/n if n else float("nan"))
    L.append(f"| {side} (n={len(G)}) | "+" | ".join(f"{v:,.0f}" for v in vals)+" |")
L+=["","## Interpretation columns (issuance beside outlay)",
    "Written after the run — see the table values above; the reading in",
    "FINDINGS.md carries the adjudicated sentence.",""]
open("analysis/P5_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
