#!/usr/bin/env python3
"""RD analysis on the paper panel (rd_sample, bond_go): three paper exhibits.
 1. BALANCE at the cutoff: pre-vote GFD covariates, barely-passed vs barely-failed.
 2. DENSITY (E2): margin histogram near 0; simple McCrary proxy (binomial test
    on counts just-above vs just-below).
 3. RD ESTIMATES: local-linear, triangular kernel, sharp RD in the margin;
    HC0 (sandwich) SEs per side; outcomes issued_6y, GO-issue, n_issues_6y,
    resubmitted_4y (failed side is the complement question - reported via the
    full-sample later-measure rate discontinuity: prob a later same-unit+class
    measure within 4y).
Pure stdlib. Writes analysis/RD_RESULTS.md; all numbers from here."""
import csv, math
from collections import Counter

PANEL="analysis/paper_panel.csv"
rows=[r for r in csv.DictReader(open(PANEL))]
def f(x):
    try: return float(x)
    except: return None

# estimation frame: institutional cutoff + GO bond measure + margin present
S=[r for r in rows if str(r["rd_sample"])=="1" and r["purpose_class"]=="bond_go"
   and f(r["threshold_centered_margin"]) is not None]
for r in S: r["_m"]=f(r["threshold_centered_margin"])
print(f"frame: rd_sample & bond_go & margin: {len(S)} referenda")
print("by state:",dict(Counter(r["state"] for r in S)))

def outcome(r,name):
    if name=="issued_6y": return float(r["issued_6y"]) if r["issued_6y"]!="" else None
    if name=="go_issue":
        if r["issued_6y"]=="":return None
        gs=f(r["go_share_6y"]); return 1.0 if (r["issued_6y"]=="1" and gs and gs>0) else 0.0
    if name=="n_issues_6y": return f(r["n_issues_6y"])
    if name=="later_measure_4y":
        # prob any later same-unit+class measure <=4y (resubmitted_4y defined for failed;
        # for passed use prior computation? panel stores it only for failed) -> use
        # resubmitted_4y where present else None (failed-side descriptive)
        v=r["resubmitted_4y"]; return float(v) if v in ("0","1") else None
    v=f(r.get(name)); return v

def wls_side(data,bw):
    """triangular-kernel local-linear fit on one side; returns (alpha, var_alpha, n)."""
    pts=[(m,y) for m,y in data if 0<abs(m)<=bw]
    n=len(pts)
    if n<10: return None,None,n
    # X=[1,m]; W=tri
    S0=S1=S2=Sy=Smy=0.0
    for m,y in pts:
        w=1-abs(m)/bw
        S0+=w; S1+=w*m; S2+=w*m*m; Sy+=w*y; Smy+=w*m*y
    det=S0*S2-S1*S1
    if det<=0: return None,None,n
    a=(S2*Sy-S1*Smy)/det; b=(S0*Smy-S1*Sy)/det
    # HC0 sandwich for alpha: (X'WX)^-1 X'W e e' W X (X'WX)^-1, alpha component
    inv=[[S2/det,-S1/det],[-S1/det,S0/det]]
    B00=B01=B11=0.0
    for m,y in pts:
        w=1-abs(m)/bw; e=y-a-b*m; we2=(w*e)**2
        B00+=we2; B01+=we2*m; B11+=we2*m*m
    va=(inv[0][0]**2)*B00+2*inv[0][0]*inv[0][1]*B01+(inv[0][1]**2)*B11
    return a,va,n

def rd(dep,S,bw):
    dl=[(r["_m"],outcome(r,dep)) for r in S if r["_m"]<0]
    dr=[(r["_m"],outcome(r,dep)) for r in S if r["_m"]>0]
    dl=[(m,y) for m,y in dl if y is not None]; dr=[(m,y) for m,y in dr if y is not None]
    aL,vL,nL=wls_side(dl,bw); aR,vR,nR=wls_side(dr,bw)
    if aL is None or aR is None: return None
    tau=aR-aL; se=math.sqrt(vL+vR); z=tau/se if se>0 else 0
    return dict(tau=tau,se=se,z=z,nL=nL,nR=nR,aL=aL,aR=aR)

L=["# RD analysis — rd_sample ∩ bond_go (GO-bond measures at a genuine mandatory-ballot cutoff)\n",
   f"Frame: **{len(S)}** referenda ({dict(Counter(r['state'] for r in S))}).",
   "Generated by `rd_analysis.py`; local-linear, triangular kernel, HC0 SEs.\n"]

# ---------- 1. balance ----------
L.append("## 1 · Covariate balance at the cutoff (±5pp, pre-vote GFD values)")
L.append("| covariate | barely-passed mean | barely-failed mean | diff | t |")
L.append("|---|--:|--:|--:|--:|")
COVS=[("gfd_pop","population"),("gfd_rev_pc","revenue per capita ($)"),
      ("gfd_debt_pc","debt outstanding p.c. ($)"),("gfd_total_rev","total revenue ($k)"),
      ("gfd_property_tax","property tax ($k)"),("gfd_enrollment","enrollment"),
      ("prior_fail_4y","prior failure ≤4y (share)")]
imbal=0
for c,lab in COVS:
    win=[f(r[c]) for r in S if 0<r["_m"]<=5 and f(r[c]) is not None]
    los=[f(r[c]) for r in S if -5<=r["_m"]<0 and f(r[c]) is not None]
    if len(win)<20 or len(los)<20: continue
    mw=sum(win)/len(win); ml=sum(los)/len(los)
    vw=sum((x-mw)**2 for x in win)/(len(win)-1); vl=sum((x-ml)**2 for x in los)/(len(los)-1)
    se=math.sqrt(vw/len(win)+vl/len(los)); t=(mw-ml)/se if se>0 else 0
    if abs(t)>1.96: imbal+=1
    L.append(f"| {lab} | {mw:,.1f} | {ml:,.1f} | {mw-ml:,.1f} | {t:.2f} |")
L.append(f"\nCovariates with |t|>1.96: **{imbal}** of {len(COVS)} tested.\n")

# ---------- 2. density ----------
L.append("## 2 · Density of the running variable near the cutoff (McCrary proxy)")
bins=Counter()
for r in S:
    m=r["_m"]
    if -5<=m<=5 and m!=0: bins[math.floor(m)]+=1
L.append("| margin bin | n |"); L.append("|---|--:|")
for b in range(-5,5): L.append(f"| [{b},{b+1}) | {bins.get(b,0)} |")
just_a=bins.get(0,0); just_b=bins.get(-1,0)
n=just_a+just_b; p=just_a/n if n else 0
zden=(just_a-n/2)/math.sqrt(n/4) if n else 0
L.append(f"\nJust-above [0,1): **{just_a}** vs just-below [−1,0): **{just_b}** → share above "
         f"{p:.3f}, binomial z = **{zden:.2f}** (|z|>1.96 flags excess mass on one side — pair with a formal McCrary/Cattaneo test and a donut-RD robustness check).\n")

# ---------- 3. RD estimates ----------
L.append("## 3 · Local-linear RD estimates (τ = jump at the cutoff)")
L.append("| outcome | bw | τ | SE | z | n (L/R) | mean left of 0 |")
L.append("|---|--:|--:|--:|--:|---|--:|")
for dep,lab in [("issued_6y","any issuance ≤6y"),("go_issue","GO issuance ≤6y"),
                ("n_issues_6y","# issues ≤6y"),("later_measure_4y","re-submission ≤4y (failed side desc.)")]:
    for bw in (5,10):
        res=rd(dep,S,bw)
        if not res: continue
        L.append(f"| {lab} | ±{bw} | {res['tau']:+.3f} | {res['se']:.3f} | {res['z']:.2f} "
                 f"| {res['nL']}/{res['nR']} | {res['aL']:.3f} |")
L.append("")
# per-state tau for the headline outcome
L.append("### Per-state τ, GO issuance ≤6y, bw ±10")
L.append("| state | τ | SE | z | n L/R |"); L.append("|---|--:|--:|--:|---|")
for st in sorted(set(r["state"] for r in S)):
    Ss=[r for r in S if r["state"]==st]
    res=rd("go_issue",Ss,10)
    if res: L.append(f"| {st} | {res['tau']:+.3f} | {res['se']:.3f} | {res['z']:.2f} | {res['nL']}/{res['nR']} |")

open("analysis/RD_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
