#!/usr/bin/env python3
"""N6 — reform-event designs: CA Prop 39 (2000) and OR Measure 56 (2008).

A · PROP 39 (Nov 2000: CA school GO threshold 66.7% → 55%; SCHOOLS ONLY).
  Data: national GFD school + municipal compacts, 1997–2007 (annual universe
  coverage from 1997; 1993–96 sample years EXCLUDED). Outcome per district-year:
  ln(1 + LTD_Issued·1000 / Enrollment) (schools; per-pupil $) and
  ln(1 + LTD_Issued·1000 / Population) (municipals).
  Designs, on state×year cell means (unweighted across districts):
    DiD   schools only: CA×post(2001–07), state FE + year FE
    DDD   y_diff_st = ȳ_school,st − ȳ_muni,st  (within-state sector difference
          absorbs state×year shocks), then CA×post with state FE + year FE
    EVENT CA×year coefficients (schools), normalized to 2000
    PERMUTATION inference: re-run the DDD assigning treatment to each other
    state; p = rank of |CA| among all placebo |β| (one treated cluster —
    Conley–Taber-style, preferred over the cluster SE here).
B · MEASURE 56 (Nov 2008: OR repeals the 1996–97 double-majority turnout
  requirement for May/November elections). Same machinery: schools + munis
  pooled sector-by-sector, 2004–2013, OR×post(2009–13), permutation inference.
FLAGS in results. Writes analysis/REFORM_DID_RESULTS.md."""
import csv, gzip, math
from collections import defaultdict

def fl(x):
    try: return float(x)
    except: return None

def load(path, denom):
    cells=defaultdict(list)   # (fips_st, year) -> [y]
    with gzip.open(f"inputs/gfd/{path}","rt") as fh:
        for r in csv.DictReader(fh):
            y=int(r["Year4"])
            if not 1997<=y<=2013: continue
            d=fl(r[denom])
            if not d or d<=0: continue
            v=max(0.0, fl(r["Total_LTD_Issued"]) or 0.0)
            st=(r["FIPS_Code_State"] or "").zfill(2)
            cells[(st,y)].append(math.log1p(v*1000/d))
    return {k:sum(v)/len(v) for k,v in cells.items() if len(v)>=20}
sch=load("gfd_school_compact.csv.gz","Enrollment")
mun=load("gfd_municipal_compact.csv.gz","Population")

def linsolve(A,b):
    n=len(A); M=[row[:]+[b[i]] for i,row in enumerate(A)]
    for c in range(n):
        p=max(range(c,n),key=lambda r:abs(M[r][c]))
        if abs(M[p][c])<1e-10: M[p][c]=1e-10
        M[c],M[p]=M[p],M[c]
        for r in range(n):
            if r!=c:
                f=M[r][c]/M[c][c]
                for k in range(c,n+1): M[r][k]-=f*M[c][k]
    return [M[i][n]/M[i][i] for i in range(n)]

def did(cells, treated, years, post_from, extra_terms=None):
    """cells: {(st,yr):y}. FE: state + year dummies; coefficient on treat×post
    (plus optional extra named terms fn(st,yr)->0/1). Returns dict name->beta."""
    obs=[(st,yr,v) for (st,yr),v in cells.items() if yr in years]
    states=sorted({st for st,_,_ in obs}); yrs=sorted({y for _,y,_ in obs})
    names=(["const","TP"]+(list(extra_terms) if extra_terms else [])
           +[f"s_{s}" for s in states[1:]]+[f"y_{y}" for y in yrs[1:]])
    p=len(names); XtX=[[0.0]*p for _ in range(p)]; Xty=[0.0]*p
    def xrow(st,yr):
        x=[0.0]*p; x[0]=1.0
        x[1]=1.0 if (st==treated and yr>=post_from) else 0.0
        i=2
        if extra_terms:
            for nm,fn in extra_terms.items(): x[names.index(nm)]=fn(st,yr)
        for j,s in enumerate(states[1:]):
            if st==s: x[2+(len(extra_terms) if extra_terms else 0)+j]=1.0
        base=2+(len(extra_terms) if extra_terms else 0)+len(states)-1
        for j,y in enumerate(yrs[1:]):
            if yr==y: x[base+j]=1.0
        return x
    for st,yr,v in obs:
        x=xrow(st,yr)
        for i in range(p):
            if x[i]:
                Xty[i]+=x[i]*v
                for j in range(i,p):
                    if x[j]: XtX[i][j]+=x[i]*x[j]
    for i in range(p):
        for j in range(i): XtX[i][j]=XtX[j][i]
    beta=linsolve(XtX,Xty)
    return beta[1],len(obs),states

def event(cells, treated, years, ref):
    """CA×year coefficients ≡ (y_CA,t − ȳ_others,t) normalized at ref."""
    out={}
    for y in years:
        ca=cells.get((treated,y))
        oth=[v for (s,t),v in cells.items() if t==y and s!=treated]
        if ca is None or not oth: out[y]=None
        else: out[y]=ca-sum(oth)/len(oth)
    base=out.get(ref)
    return {y:(v-base if v is not None and base is not None else None) for y,v in out.items()}

L=["# N6 — reform-event designs (Prop 39 · Measure 56)\n","Generated by `reform_did.py`.",
   "State×year cell means (≥20 districts/cell), FE by state and year; single-treated-",
   "state inference by PERMUTATION (placebo reassignment), not the cluster SE.\n"]

# ---------- A: Prop 39 ----------
Y=range(1997,2008); CA="06"
b_sch,n1,states=did(sch,CA,Y,2001)
diff={}
for (st,y),v in sch.items():
    if (st,y) in mun and y in Y: diff[(st,y)]=v-mun[(st,y)]
b_ddd,n2,states2=did(diff,CA,Y,2001)
# permutation
perm=[]
for s in states2:
    if s==CA: continue
    perm.append(abs(did(diff,s,Y,2001)[0]))
p_perm=(sum(1 for x in perm if x>=abs(b_ddd))+1)/(len(perm)+1)
perm_s=[abs(did(sch,s,Y,2001)[0]) for s in states if s!=CA]
p_perm_s=(sum(1 for x in perm_s if x>=abs(b_sch))+1)/(len(perm_s)+1)
ev=event(sch,CA,Y,2000)
L+=["## A · CA Prop 39 (Nov 2000): 66.7% → 55%, schools only",
    f"Cells: schools n={n1}, sector-differenced n={n2} ({len(states2)} states).",
    "| design | β (CA×post 2001–07) | permutation p |","|---|--:|--:|",
    f"| DiD, schools (CA vs all states) | **{b_sch:+.3f}** | {p_perm_s:.3f} |",
    f"| DDD, school−muni within state | **{b_ddd:+.3f}** | {p_perm:.3f} |",
    "","Event study (schools): CA − other-state mean, ln per-pupil issuance, normalized 2000:",
    "| year | "+" | ".join(str(y) for y in Y)+" |","|---|"+"--:|"*len(Y)]
L.append("| CA gap | "+" | ".join(f"{ev[y]:+.2f}" if ev[y] is not None else "–" for y in Y)+" |")
L+=["","Scale note: β is a log-point shift in mean per-pupil LTD issuance;",
    f"exp({b_ddd:.3f})−1 ≈ {math.exp(b_ddd)-1:+.0%} relative to the counterfactual.",""]

# ---------- A2: FFC composition — DEGENERATE (documented, not estimated) ----------
# Intended sharp margin: Prop 39 shifts CA schools INTO voted GO (FFC) debt.
# FINDING: in GFD 1997–2004 the school FFC share of issued LTD is EXACTLY 1.000
# in every state-year cell (NG=0 for all school unit-years) — the Census
# classification assigns all school LTD to full-faith-credit by convention, so
# the composition margin does not exist in this source.
deg=defaultdict(lambda:[0.0,0.0])
with gzip.open("inputs/gfd/gfd_school_compact.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        if "1997"<=r["Year4"]<="2004":
            deg[r["Year4"]][0]+=max(0.0,fl(r["Total_LTD_Iss_FFC"]) or 0.0)
            deg[r["Year4"]][1]+=max(0.0,fl(r["Total_LTD_Issued"]) or 0.0)
all_one=all(abs(a/b-1.0)<1e-9 for a,b in deg.values() if b>0)
L+=["## A2 · FFC (voted GO) composition — DEGENERATE outcome, documented",
    f"School FFC share of issued LTD 1997–2004 is exactly 1.000 in every year "
    f"(verified: {all_one}) — GFD assigns ALL school LTD to full-faith-credit by "
    "convention (NG is enterprise/revenue debt, which schools do not hold in the "
    "classification). The Prop-39 composition margin (COPs/leases → voted GO) is "
    "INVISIBLE in GFD. Correct source for the upgrade: the CDIAC debt-issuance "
    "database (all CA local issues since ~1985, with debt type: COP vs GO) — a "
    "within-CA school event study around 2000 on the GO share of school issuance. "
    "TO DO (data pull, not yet in repo).",""]

# ---------- B: Measure 56 ----------
Y2=range(2004,2014); OR="41"
diff2={}
for (st,y),v in sch.items():
    if (st,y) in mun and y in Y2: diff2[(st,y)]=v-mun[(st,y)]
b_or_s,n3,st3=did(sch,OR,Y2,2009)
b_or_m,_,_=did(mun,OR,Y2,2009)
perm_or=[abs(did(sch,s,Y2,2009)[0]) for s in st3 if s!=OR]
p_or=(sum(1 for x in perm_or if x>=abs(b_or_s))+1)/(len(perm_or)+1)
ev_or=event(sch,OR,Y2,2008)
L+=["## B · OR Measure 56 (Nov 2008): double-majority repeal (May/Nov elections)",
    "| design | β (OR×post 2009–13) | permutation p |","|---|--:|--:|",
    f"| DiD, schools | **{b_or_s:+.3f}** | {p_or:.3f} |",
    f"| DiD, municipals | {b_or_m:+.3f} | – |",
    "","Event study (schools): OR − other-state mean, normalized 2008:",
    "| year | "+" | ".join(str(y) for y in Y2)+" |","|---|"+"--:|"*len(Y2)]
L.append("| OR gap | "+" | ".join(f"{ev_or[y]:+.2f}" if ev_or[y] is not None else "–" for y in Y2)+" |")

L+=["","## FLAGS — what these designs still need",
    "1. **Prop 39 confounds:** the measure bundled accountability provisions, and CA's",
    "   state school-facility matching bonds (Prop 47 in 2002, Prop 55 in 2004) raised",
    "   school construction money in the same window — the DDD nets state×year shocks",
    "   but NOT school-specific CA programs. TO DO: control the state-match flow",
    "   (OPSC apportionments) or restrict to districts below the matching cap.",
    "2. **Single treated state:** permutation p is the honest test (49 placebos);",
    "   pre-trend visible in the event row must be weighed (1997–2000 gap drift).",
    "3. **GFD years 1993–96 are sample-only** (≈4k school rows/yr) — excluded; the",
    "   pre-window is 1997–2000 (4 years).",
    "4. **Denominators:** enrollment for schools, population for munis; the sector",
    "   difference mixes them (levels differ; FE absorb, trends may not).",
    "5. **Measure 56 sits on the financial crisis** (2008–09): OR's construction",
    "   downturn was deeper than average — the school-vs-muni contrast within OR",
    "   (not run: muni cells thin) and an off-cycle-share outcome (not in GFD —",
    "   needs OR election records) are the required upgrades. Treat B as a sketch.",
    "6. **No unit-level design yet:** cells are state×year means; a district-level",
    "   two-way FE version with enrollment weights + Conley–Taber CIs is the",
    "   publishable upgrade for A.",
    "7. Rules pass-2 does not gate these designs (treatment = the reform event,",
    "   not the coded panel) — A is the strongest national causal object available."]
open("analysis/REFORM_DID_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
