#!/usr/bin/env python3
"""Rows 8 + 11 — the authority layer in the theory's own vocabulary.

TRANSITION MATRIX (row 8). Frame rd_sample ∩ bond_go, close window |margin|<=5:
for each referendum, the REALIZED AUTHORIZER of the unit's FIRST new-money issue
within 6y (voter / council_or_board / statutory / other-mode / none). Rows
barely-passed vs barely-failed, row-normalized: what authority does borrowing
actually ride on, either side of the cutoff?

FATE TABLE (row 11). Cohort: FAILED bond_go measures 2005–2019 (full 6y EMMA
window; >=4y return observability). Mutually exclusive fates per 100 refused:
  A CONVERTED BY RE-VOTE   a same-unit+class return <=4y that PASSED
  B RETURNED, UNCONVERTED  return <=4y, none passed <=4y
  C NO RETURN, ISSUED ANYWAY <=6y — subdivided by realized channel of the first
     issue: council/statutory (substitution), voter (old authorization), other
  D EXTINGUISHED (horizon) no return <=4y, no new-money issue <=6y
Reported for all failures and for close failures (|margin|<=5, the causal margin).
Writes analysis/TRANSITION_FATE_RESULTS.md. All numbers from this script."""
import csv, gzip, datetime as dt
from collections import defaultdict, Counter

def f(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

rows=list(csv.DictReader(open("analysis/paper_panel.csv")))
# unit -> [(date, auth_mode, new_money)] sorted
iss=defaultdict(list)
with gzip.open("analysis/cache/issuance_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        d=pdate(r["dated_date"])
        if not d: continue
        nm=(r.get("has_new_money","").lower() in ("true","1")) and (r.get("has_refunding","").lower() not in ("true","1"))
        iss[(r["pol_accountable_unit_id"] or "")[:9]].append((d,r.get("auth_mode_final2") or "",nm))
for k in iss: iss[k].sort()
def first_issue_mode(u,d,years=6):
    for dd,am,nm in iss.get(u,[]):
        if nm and dt.timedelta(0)<dd-d<=dt.timedelta(days=int(years*365.25)):
            return am if am in ("voter","council_or_board","statutory") else "other/unknown"
    return None

# election sequences for returns
seq=defaultdict(list); last_by_state=defaultdict(lambda: dt.date(1900,1,1))
for r in rows:
    d=pdate(r["election_date"])
    if d and d>last_by_state[r["state"]]: last_by_state[r["state"]]=d
    if r["unit_id"] and d: seq[(r["unit_id"],r["purpose_class"])].append((d,r["passed"]))
for k in seq: seq[k].sort()
def returns_4y(r):
    d=pdate(r["election_date"])
    rs=[(dj,pj) for dj,pj in seq[(r["unit_id"],r["purpose_class"])] if dt.timedelta(0)<dj-d<=dt.timedelta(days=1461)]
    return (len(rs)>0, any(p=="1" for _,p in rs))

L=["# Transition matrix & fate table (rows 8, 11)\n","Generated by `transition_fate.py`.\n"]

# ---------- transition matrix ----------
S=[r for r in rows if str(r["rd_sample"])=="1" and r["purpose_class"]=="bond_go"
   and f(r["threshold_centered_margin"]) is not None]
MODES=["voter","council_or_board","statutory","other/unknown",None]
LAB={"voter":"voter","council_or_board":"council","statutory":"statutory","other/unknown":"other",None:"no issue ≤6y"}
L+=["## Row 8 · Realized authorizer of the FIRST post-vote new-money issue (|margin|≤5)",
    "| vote outcome | n | "+" | ".join(LAB[m] for m in MODES)+" |",
    "|---|--:|"+"--:|"*len(MODES)]
for side,lab in [(lambda m:0<m<=5,"barely-PASSED"),(lambda m:-5<=m<0,"barely-FAILED")]:
    G=[r for r in S if side(f(r["threshold_centered_margin"]))]
    c=Counter(first_issue_mode((r["unit_id"] or "")[:9],pdate(r["election_date"])) for r in G if pdate(r["election_date"]))
    n=sum(c.values())
    L.append(f"| {lab} | {n} | "+" | ".join(f"{c.get(m,0)/n:.1%}" for m in MODES)+" |")
L.append("")

# ---------- fate table ----------
def fate_table(fails,title):
    A=B=Cc=Cv=Co=D=0
    for r in fails:
        d=pdate(r["election_date"]); u=(r["unit_id"] or "")[:9]
        ret,conv=returns_4y(r)
        if ret and conv: A+=1
        elif ret: B+=1
        else:
            m=first_issue_mode(u,d)
            if m in ("council_or_board","statutory"): Cc+=1
            elif m=="voter": Cv+=1
            elif m is not None: Co+=1
            else: D+=1
    n=len(fails)
    out=[f"### {title} (n={n})","| fate per 100 refused | share |","|---|--:|",
         f"| A · converted by re-vote (return ≤4y passed) | {A/n:.1%} |",
         f"| B · returned ≤4y, not (yet) converted | {B/n:.1%} |",
         f"| C · no return — issued anyway ≤6y via council/statutory | {Cc/n:.1%} |",
         f"| C′ · no return — issued via VOTER mode (old authorization) | {Cv/n:.1%} |",
         f"| C″ · no return — issued, channel other/unknown | {Co/n:.1%} |",
         f"| D · extinguished within horizon (no return, no issue) | {D/n:.1%} |",""]
    return out
cohort=[r for r in rows if r["purpose_class"]=="bond_go" and r["passed"]=="0"
        and pdate(r["election_date"]) and 2005<=pdate(r["election_date"]).year<=2019
        and r["unit_id"]
        and (last_by_state[r["state"]]-pdate(r["election_date"])).days>=1461]
L.append("## Row 11 · The fate of refusal (failures 2005–2019, full windows)")
L+=fate_table(cohort,"All refused GO-bond measures")
close=[r for r in cohort if f(r["threshold_centered_margin"]) is not None and -5<=f(r["threshold_centered_margin"])<0]
L+=fate_table(close,"Barely refused (|margin|≤5 — the causal margin)")

open("analysis/TRANSITION_FATE_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
