#!/usr/bin/env python3
"""Row 18 — measurement validation: OS-extracted authorization fields vs
election-record truth, in the 9 states where we hold the truth.

Three tests (per state + pooled), from paper_panel + cache/issuance_subset:
 T1 DATE MATCH.  Among issuance docs (of crosswalked units) carrying an
    extracted election_date: share matching a referendum we observe for that
    unit (exact day; ±7d), and — conditional on a match — share where that
    referendum PASSED (an OS citing a failed election would be an extraction
    error). Runs on the ~5%-filled election_date subset (tier-2 lifts it).
 T2 VOTER-MODE SUPPORT.  Among VOTER-authorized new-money docs of units in the
    election states: share whose unit has a PASSED referendum (any class) in the
    prior 6y in our records — the election record 'supports' the OS claim.
    (Shortfall = registry coverage gaps + pre-2005/pre-frame authorizations +
    mode errors; an upper bound on error, not an error rate.)
 T3 COUNCIL-MODE CONSISTENCY.  Among COUNCIL-authorized new-money docs: share
    whose unit had NO passed GO referendum in the prior 2y (a passed GO vote
    immediately before a council-mode doc is *suggestive* of mode error —
    weak evidence only, units run both channels concurrently).
Writes analysis/VALIDATION_RESULTS.md. All numbers from this script."""
import csv, gzip, datetime as dt
from collections import defaultdict

def f(x):
    try: return float(x)
    except: return None
def pdate(s):
    try: return dt.date.fromisoformat((s or "")[:10])
    except: return None

# election truth: unit9 -> [(date, passed, purpose_class)]
truth=defaultdict(list)
states_of=defaultdict(set)
for r in csv.DictReader(open("analysis/paper_panel.csv")):
    d=pdate(r["election_date"])
    if r["unit_id"] and d:
        truth[r["unit_id"][:9]].append((d,r["passed"],r["purpose_class"]))
        states_of[r["unit_id"][:9]].add(r["state"])
for k in truth: truth[k].sort()

T1=defaultdict(lambda:[0,0,0,0])  # state -> [docs_w_date, exact, within7, matched_passed]
T2=defaultdict(lambda:[0,0])      # state -> [voter_docs, supported]
T3=defaultdict(lambda:[0,0])      # state -> [council_docs, no_recent_passed_go]
with gzip.open("analysis/cache/issuance_subset.csv.gz","rt") as fh:
    for r in csv.DictReader(fh):
        u=(r["pol_accountable_unit_id"] or "")[:9]
        if u not in truth: continue
        st=r["state"]
        dd=pdate(r["dated_date"])
        am=r.get("auth_mode_final2") or ""
        nm=(r.get("has_new_money","").lower() in ("true","1"))
        ed=pdate(r.get("election_date"))
        if ed:
            T1[st][0]+=1
            hits=[(abs((ed-t).days),p) for t,p,_ in truth[u]]
            if hits:
                dmin,p=min(hits)
                if dmin==0:
                    T1[st][1]+=1; T1[st][2]+=1
                    if p=="1": T1[st][3]+=1
                elif dmin<=7:
                    T1[st][2]+=1
        if not (dd and nm): continue
        if am=="voter":
            T2[st][0]+=1
            if any(p=="1" and dt.timedelta(0)<=dd-t<=dt.timedelta(days=2192) for t,p,_ in truth[u]):
                T2[st][1]+=1
        elif am=="council_or_board":
            T3[st][0]+=1
            if not any(p=="1" and c=="bond_go" and dt.timedelta(0)<=dd-t<=dt.timedelta(days=731) for t,p,c in truth[u]):
                T3[st][1]+=1

L=["# Validation — OS authorization fields vs election-record truth (row 18)\n",
   "Generated by `validation_join.py`. Docs restricted to crosswalked units in the",
   "9 election states; see script header for test definitions and caveats.\n",
   "| state | T1: docs w/ date | exact match | ±7d | matched→PASSED | T2: voter docs | supported ≤6y | T3: council docs | no recent passed GO |",
   "|---|--:|--:|--:|--:|--:|--:|--:|--:|"]
def pct(a,b): return f"{a/b:.1%}" if b else "–"
tot=[0]*8
for st in sorted(set(list(T1)+list(T2)+list(T3))):
    a=T1[st]; b=T2[st]; c=T3[st]
    tot=[tot[0]+a[0],tot[1]+a[1],tot[2]+a[2],tot[3]+a[3],tot[4]+b[0],tot[5]+b[1],tot[6]+c[0],tot[7]+c[1]]
    L.append(f"| {st} | {a[0]} | {pct(a[1],a[0])} | {pct(a[2],a[0])} | {pct(a[3],a[1])} "
             f"| {b[0]} | {pct(b[1],b[0])} | {c[0]} | {pct(c[1],c[0])} |")
L.append(f"| **pooled** | {tot[0]} | {pct(tot[1],tot[0])} | {pct(tot[2],tot[0])} | {pct(tot[3],tot[1])} "
         f"| {tot[4]} | {pct(tot[5],tot[4])} | {tot[6]} | {pct(tot[7],tot[6])} |")
open("analysis/VALIDATION_RESULTS.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
